// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: payment.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO
    payments (
        order_id,
        amount,
        method
    )
VALUES
    (
        $1,
        $2,
        $3
    )
RETURNING id, order_id, amount, method, status, gateway, transaction_id, created_at, updated_at
`

type CreatePaymentTransactionParams struct {
	OrderID int64          `json:"order_id"`
	Amount  pgtype.Numeric `json:"amount"`
	Method  PaymentMethod  `json:"method"`
}

func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction, arg.OrderID, arg.Amount, arg.Method)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Amount,
		&i.Method,
		&i.Status,
		&i.Gateway,
		&i.TransactionID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
