// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	AddProductToCart(ctx context.Context, arg AddProductToCartParams) (CartItem, error)
	ArchiveProduct(ctx context.Context, id int64) error
	ClearCart(ctx context.Context, cartID int64) error
	CountCartItem(ctx context.Context, cartID int64) (int64, error)
	CreateAddress(ctx context.Context, arg CreateAddressParams) (UserAddress, error)
	CreateCart(ctx context.Context, userID int64) (Cart, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteOrder(ctx context.Context, id int64) error
	DeleteProduct(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	GetAddress(ctx context.Context, arg GetAddressParams) (UserAddress, error)
	GetCart(ctx context.Context, userID int64) (Cart, error)
	GetCartDetail(ctx context.Context, userID int64) ([]GetCartDetailRow, error)
	GetCartItem(ctx context.Context, id int64) (CartItem, error)
	GetOrder(ctx context.Context, id int64) (Order, error)
	GetOrderDetails(ctx context.Context, id int64) ([]GetOrderDetailsRow, error)
	GetProduct(ctx context.Context, id int64) (Product, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	ListAddresses(ctx context.Context, arg ListAddressesParams) ([]UserAddress, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListOrders(ctx context.Context, arg ListOrdersParams) ([]ListOrdersRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveProductFromCart(ctx context.Context, arg RemoveProductFromCartParams) error
	ResetPrimaryAddress(ctx context.Context, userID int64) error
	SetCartCheckoutAt(ctx context.Context, arg SetCartCheckoutAtParams) error
	SetPrimaryAddress(ctx context.Context, arg SetPrimaryAddressParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UserAddress, error)
	UpdateCart(ctx context.Context, id int64) error
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
