// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForAddVariantAttributes implements pgx.CopyFromSource.
type iteratorForAddVariantAttributes struct {
	rows                 []AddVariantAttributesParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddVariantAttributes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddVariantAttributes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].VariantID,
		r.rows[0].AttributeValueID,
	}, nil
}

func (r iteratorForAddVariantAttributes) Err() error {
	return nil
}

func (q *Queries) AddVariantAttributes(ctx context.Context, arg []AddVariantAttributesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"variant_attributes"}, []string{"variant_id", "attribute_value_id"}, &iteratorForAddVariantAttributes{rows: arg})
}

// iteratorForSeedAddresses implements pgx.CopyFromSource.
type iteratorForSeedAddresses struct {
	rows                 []SeedAddressesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedAddresses) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedAddresses) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].Phone,
		r.rows[0].Street,
		r.rows[0].Ward,
		r.rows[0].District,
		r.rows[0].City,
		r.rows[0].Default,
	}, nil
}

func (r iteratorForSeedAddresses) Err() error {
	return nil
}

func (q *Queries) SeedAddresses(ctx context.Context, arg []SeedAddressesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_addresses"}, []string{"user_id", "phone", "street", "ward", "district", "city", "default"}, &iteratorForSeedAddresses{rows: arg})
}

// iteratorForSeedAttributeValues implements pgx.CopyFromSource.
type iteratorForSeedAttributeValues struct {
	rows                 []SeedAttributeValuesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedAttributeValues) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedAttributeValues) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AttributeID,
		r.rows[0].AttributeValue,
	}, nil
}

func (r iteratorForSeedAttributeValues) Err() error {
	return nil
}

func (q *Queries) SeedAttributeValues(ctx context.Context, arg []SeedAttributeValuesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attribute_values"}, []string{"attribute_id", "attribute_value"}, &iteratorForSeedAttributeValues{rows: arg})
}

// iteratorForSeedAttributes implements pgx.CopyFromSource.
type iteratorForSeedAttributes struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForSeedAttributes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedAttributes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForSeedAttributes) Err() error {
	return nil
}

func (q *Queries) SeedAttributes(ctx context.Context, attributeName []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attributes"}, []string{"attribute_name"}, &iteratorForSeedAttributes{rows: attributeName})
}

// iteratorForSeedCollections implements pgx.CopyFromSource.
type iteratorForSeedCollections struct {
	rows                 []SeedCollectionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedCollections) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedCollections) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].SortOrder,
		r.rows[0].Published,
	}, nil
}

func (r iteratorForSeedCollections) Err() error {
	return nil
}

func (q *Queries) SeedCollections(ctx context.Context, arg []SeedCollectionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"categories"}, []string{"name", "description", "sort_order", "published"}, &iteratorForSeedCollections{rows: arg})
}

// iteratorForSeedProducts implements pgx.CopyFromSource.
type iteratorForSeedProducts struct {
	rows                 []SeedProductsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedProducts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedProducts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Sku,
		r.rows[0].Stock,
		r.rows[0].Price,
		r.rows[0].Discount,
	}, nil
}

func (r iteratorForSeedProducts) Err() error {
	return nil
}

func (q *Queries) SeedProducts(ctx context.Context, arg []SeedProductsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"products"}, []string{"name", "description", "sku", "stock", "price", "discount"}, &iteratorForSeedProducts{rows: arg})
}

// iteratorForSeedUsers implements pgx.CopyFromSource.
type iteratorForSeedUsers struct {
	rows                 []SeedUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Email,
		r.rows[0].Username,
		r.rows[0].Phone,
		r.rows[0].Fullname,
		r.rows[0].HashedPassword,
		r.rows[0].Role,
	}, nil
}

func (r iteratorForSeedUsers) Err() error {
	return nil
}

func (q *Queries) SeedUsers(ctx context.Context, arg []SeedUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"email", "username", "phone", "fullname", "hashed_password", "role"}, &iteratorForSeedUsers{rows: arg})
}
