// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: attributes.sql

package repository

import (
	"context"

	"github.com/google/uuid"
)

const countAttributes = `-- name: CountAttributes :one
SELECT COUNT(*) FROM attributes
`

func (q *Queries) CountAttributes(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countAttributes)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAttribute = `-- name: CreateAttribute :one
INSERT INTO attributes (name) VALUES ($1) RETURNING id, name
`

func (q *Queries) CreateAttribute(ctx context.Context, name string) (Attribute, error) {
	row := q.db.QueryRow(ctx, createAttribute, name)
	var i Attribute
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const createAttributeValue = `-- name: CreateAttributeValue :one
INSERT INTO attribute_values (attribute_id, value) VALUES ($1, $2) RETURNING id, attribute_id, value
`

type CreateAttributeValueParams struct {
	AttributeID int32  `json:"attributeId"`
	Value       string `json:"value"`
}

// Attribute values
func (q *Queries) CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error) {
	row := q.db.QueryRow(ctx, createAttributeValue, arg.AttributeID, arg.Value)
	var i AttributeValue
	err := row.Scan(&i.ID, &i.AttributeID, &i.Value)
	return i, err
}

type CreateAttributeValuesParams struct {
	AttributeID int32  `json:"attributeId"`
	Value       string `json:"value"`
}

type CreateBulkProductAttributesParams struct {
	ProductID   uuid.UUID `json:"productId"`
	AttributeID int32     `json:"attributeId"`
}

type CreateBulkProductVariantAttributeParams struct {
	VariantID        uuid.UUID `json:"variantId"`
	AttributeValueID int64     `json:"attributeValueId"`
}

const createProductAttribute = `-- name: CreateProductAttribute :one
INSERT INTO product_attributes (product_id, attribute_id) VALUES ($1, $2) RETURNING id, product_id, attribute_id
`

type CreateProductAttributeParams struct {
	ProductID   uuid.UUID `json:"productId"`
	AttributeID int32     `json:"attributeId"`
}

// PRODUCT ATTRIBUTES QUERIES
func (q *Queries) CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductAttribute, error) {
	row := q.db.QueryRow(ctx, createProductAttribute, arg.ProductID, arg.AttributeID)
	var i ProductAttribute
	err := row.Scan(&i.ID, &i.ProductID, &i.AttributeID)
	return i, err
}

const createProductVariantAttribute = `-- name: CreateProductVariantAttribute :one
INSERT INTO variant_attribute_values (variant_id, attribute_value_id) VALUES ($1, $2) RETURNING variant_id, attribute_value_id
`

type CreateProductVariantAttributeParams struct {
	VariantID        uuid.UUID `json:"variantId"`
	AttributeValueID int64     `json:"attributeValueId"`
}

// Product Variant attributes
func (q *Queries) CreateProductVariantAttribute(ctx context.Context, arg CreateProductVariantAttributeParams) (VariantAttributeValue, error) {
	row := q.db.QueryRow(ctx, createProductVariantAttribute, arg.VariantID, arg.AttributeValueID)
	var i VariantAttributeValue
	err := row.Scan(&i.VariantID, &i.AttributeValueID)
	return i, err
}

const deleteAttribute = `-- name: DeleteAttribute :exec
DELETE FROM attributes WHERE id = $1
`

func (q *Queries) DeleteAttribute(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteAttribute, id)
	return err
}

const deleteAttributeValue = `-- name: DeleteAttributeValue :exec
DELETE FROM attribute_values WHERE id = $1
`

func (q *Queries) DeleteAttributeValue(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteAttributeValue, id)
	return err
}

const deleteAttributeValueByValueID = `-- name: DeleteAttributeValueByValueID :exec
DELETE FROM attribute_values WHERE id = $2 AND attribute_id = $1
`

type DeleteAttributeValueByValueIDParams struct {
	AttributeID int32 `json:"attributeId"`
	ID          int64 `json:"id"`
}

func (q *Queries) DeleteAttributeValueByValueID(ctx context.Context, arg DeleteAttributeValueByValueIDParams) error {
	_, err := q.db.Exec(ctx, deleteAttributeValueByValueID, arg.AttributeID, arg.ID)
	return err
}

const deleteProductAttributesByProductID = `-- name: DeleteProductAttributesByProductID :exec
DELETE FROM product_attributes WHERE product_id = $1
`

func (q *Queries) DeleteProductAttributesByProductID(ctx context.Context, productID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductAttributesByProductID, productID)
	return err
}

const deleteProductVariantAttributes = `-- name: DeleteProductVariantAttributes :exec
DELETE FROM variant_attribute_values WHERE variant_id = $1
`

func (q *Queries) DeleteProductVariantAttributes(ctx context.Context, variantID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductVariantAttributes, variantID)
	return err
}

const getAttributeByID = `-- name: GetAttributeByID :one
SELECT id, name FROM attributes WHERE id = $1 ORDER BY id
`

func (q *Queries) GetAttributeByID(ctx context.Context, id int32) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByID, id)
	var i Attribute
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAttributeByName = `-- name: GetAttributeByName :one
SELECT id, name FROM attributes WHERE name = $1 LIMIT 1
`

func (q *Queries) GetAttributeByName(ctx context.Context, name string) (Attribute, error) {
	row := q.db.QueryRow(ctx, getAttributeByName, name)
	var i Attribute
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getAttributeValueByID = `-- name: GetAttributeValueByID :one
SELECT id, attribute_id, value FROM attribute_values WHERE id = $1
`

func (q *Queries) GetAttributeValueByID(ctx context.Context, id int64) (AttributeValue, error) {
	row := q.db.QueryRow(ctx, getAttributeValueByID, id)
	var i AttributeValue
	err := row.Scan(&i.ID, &i.AttributeID, &i.Value)
	return i, err
}

const getAttributeValues = `-- name: GetAttributeValues :many
SELECT id, attribute_id, value FROM attribute_values WHERE attribute_id = $1 ORDER BY id
`

func (q *Queries) GetAttributeValues(ctx context.Context, attributeID int32) ([]AttributeValue, error) {
	rows, err := q.db.Query(ctx, getAttributeValues, attributeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeValue{}
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(&i.ID, &i.AttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttributeValuesByIDs = `-- name: GetAttributeValuesByIDs :many
SELECT id, attribute_id, value FROM attribute_values
WHERE id = ANY($1::bigint[]) ORDER BY id
`

func (q *Queries) GetAttributeValuesByIDs(ctx context.Context, ids []int64) ([]AttributeValue, error) {
	rows, err := q.db.Query(ctx, getAttributeValuesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AttributeValue{}
	for rows.Next() {
		var i AttributeValue
		if err := rows.Scan(&i.ID, &i.AttributeID, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttributeWithValuesByIDs = `-- name: GetAttributeWithValuesByIDs :many
SELECT att.name as attribute_name, att.id as attribute_id, atv.value as attribute_value, atv.id as attribute_value_id 
FROM attributes as att
LEFT JOIN attribute_values as atv ON att.id = atv.attribute_id
WHERE attribute_id = ANY($1::int[]) 
ORDER BY atv.id
`

type GetAttributeWithValuesByIDsRow struct {
	AttributeName    string  `json:"attributeName"`
	AttributeID      int32   `json:"attributeId"`
	AttributeValue   *string `json:"attributeValue"`
	AttributeValueID *int64  `json:"attributeValueId"`
}

func (q *Queries) GetAttributeWithValuesByIDs(ctx context.Context, ids []int32) ([]GetAttributeWithValuesByIDsRow, error) {
	rows, err := q.db.Query(ctx, getAttributeWithValuesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttributeWithValuesByIDsRow{}
	for rows.Next() {
		var i GetAttributeWithValuesByIDsRow
		if err := rows.Scan(
			&i.AttributeName,
			&i.AttributeID,
			&i.AttributeValue,
			&i.AttributeValueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttributes = `-- name: GetAttributes :many
SELECT 
    a.id, a.name, av.value as attr_value, av.id as attr_value_id
FROM attributes as a
LEFT JOIN attribute_values as av ON a.id = av.attribute_id
WHERE 
    CASE 
        WHEN array_length($1::int[], 1) > 0 THEN a.id = ANY($1::int[])
        ELSE true
    END
ORDER BY a.id
`

type GetAttributesRow struct {
	ID          int32   `json:"id"`
	Name        string  `json:"name"`
	AttrValue   *string `json:"attrValue"`
	AttrValueID *int64  `json:"attrValueId"`
}

func (q *Queries) GetAttributes(ctx context.Context, ids []int32) ([]GetAttributesRow, error) {
	rows, err := q.db.Query(ctx, getAttributes, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAttributesRow{}
	for rows.Next() {
		var i GetAttributesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AttrValue,
			&i.AttrValueID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAttributesByIDs = `-- name: GetAttributesByIDs :many
SELECT id, name FROM attributes WHERE id = ANY($1::int[]) ORDER BY attributes.id
`

func (q *Queries) GetAttributesByIDs(ctx context.Context, ids []int32) ([]Attribute, error) {
	rows, err := q.db.Query(ctx, getAttributesByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Attribute{}
	for rows.Next() {
		var i Attribute
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductAttributeValuesByProductID = `-- name: GetProductAttributeValuesByProductID :many
SELECT
    a.id as attribute_id,
    a.name as attribute_name,
    av.id as attribute_value_id,
    av.value as attribute_value
FROM product_attributes as pa
LEFT JOIN attributes as a ON pa.attribute_id = a.id
LEFT JOIN attribute_values as av ON a.id = av.attribute_id
WHERE pa.product_id = $1
ORDER BY a.id, av.id
`

type GetProductAttributeValuesByProductIDRow struct {
	AttributeID      *int32  `json:"attributeId"`
	AttributeName    *string `json:"attributeName"`
	AttributeValueID *int64  `json:"attributeValueId"`
	AttributeValue   *string `json:"attributeValue"`
}

func (q *Queries) GetProductAttributeValuesByProductID(ctx context.Context, productID uuid.UUID) ([]GetProductAttributeValuesByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getProductAttributeValuesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductAttributeValuesByProductIDRow{}
	for rows.Next() {
		var i GetProductAttributeValuesByProductIDRow
		if err := rows.Scan(
			&i.AttributeID,
			&i.AttributeName,
			&i.AttributeValueID,
			&i.AttributeValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductAttributesByProductID = `-- name: GetProductAttributesByProductID :many
SELECT pa.id, pa.product_id, pa.attribute_id, a.name as attribute_name
FROM product_attributes as pa
LEFT JOIN attributes as a ON pa.attribute_id = a.id
WHERE pa.product_id = $1 ORDER BY pa.attribute_id
`

type GetProductAttributesByProductIDRow struct {
	ID            int64     `json:"id"`
	ProductID     uuid.UUID `json:"productId"`
	AttributeID   int32     `json:"attributeId"`
	AttributeName *string   `json:"attributeName"`
}

func (q *Queries) GetProductAttributesByProductID(ctx context.Context, productID uuid.UUID) ([]GetProductAttributesByProductIDRow, error) {
	rows, err := q.db.Query(ctx, getProductAttributesByProductID, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductAttributesByProductIDRow{}
	for rows.Next() {
		var i GetProductAttributesByProductIDRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.AttributeID,
			&i.AttributeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductVariantAttributeByID = `-- name: GetProductVariantAttributeByID :one
SELECT variant_id, attribute_value_id FROM variant_attribute_values WHERE variant_id = $1 LIMIT 1
`

func (q *Queries) GetProductVariantAttributeByID(ctx context.Context, variantID uuid.UUID) (VariantAttributeValue, error) {
	row := q.db.QueryRow(ctx, getProductVariantAttributeByID, variantID)
	var i VariantAttributeValue
	err := row.Scan(&i.VariantID, &i.AttributeValueID)
	return i, err
}

const getProductVariantAttributes = `-- name: GetProductVariantAttributes :many
SELECT variant_id, attribute_value_id FROM variant_attribute_values WHERE variant_id = $1 ORDER BY variant_attribute_values.attribute_value_id
`

func (q *Queries) GetProductVariantAttributes(ctx context.Context, variantID uuid.UUID) ([]VariantAttributeValue, error) {
	rows, err := q.db.Query(ctx, getProductVariantAttributes, variantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VariantAttributeValue{}
	for rows.Next() {
		var i VariantAttributeValue
		if err := rows.Scan(&i.VariantID, &i.AttributeValueID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAttribute = `-- name: UpdateAttribute :one
UPDATE attributes SET name = $1 WHERE id = $2 RETURNING id, name
`

type UpdateAttributeParams struct {
	Name string `json:"name"`
	ID   int32  `json:"id"`
}

func (q *Queries) UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error) {
	row := q.db.QueryRow(ctx, updateAttribute, arg.Name, arg.ID)
	var i Attribute
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const updateAttributeValue = `-- name: UpdateAttributeValue :one
UPDATE attribute_values 
SET value = $3
WHERE id = $1 AND attribute_id = $2 RETURNING id, attribute_id, value
`

type UpdateAttributeValueParams struct {
	ID          int64  `json:"id"`
	AttributeID int32  `json:"attributeId"`
	Value       string `json:"value"`
}

func (q *Queries) UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) (AttributeValue, error) {
	row := q.db.QueryRow(ctx, updateAttributeValue, arg.ID, arg.AttributeID, arg.Value)
	var i AttributeValue
	err := row.Scan(&i.ID, &i.AttributeID, &i.Value)
	return i, err
}
