// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const addProductToCollection = `-- name: AddProductToCollection :exec
INSERT INTO collection_products (collection_id, product_id) VALUES ($1, $2)
`

type AddProductToCollectionParams struct {
	CollectionID uuid.UUID `json:"collectionId"`
	ProductID    uuid.UUID `json:"productId"`
}

func (q *Queries) AddProductToCollection(ctx context.Context, arg AddProductToCollectionParams) error {
	_, err := q.db.Exec(ctx, addProductToCollection, arg.CollectionID, arg.ProductID)
	return err
}

const countCollections = `-- name: CountCollections :one
SELECT count(*) FROM collections
`

func (q *Queries) CountCollections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCollections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name, slug, description,  image_url, image_id) VALUES ($1, $2, $3, $4, $5) RETURNING id, name, image_url, image_id, description, slug, display_order, published, created_at, updated_at
`

type CreateCollectionParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	ImageUrl    *string `json:"imageUrl"`
	ImageID     *string `json:"imageId"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.ImageUrl,
		arg.ImageID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT id, name, image_url, image_id, description, slug, display_order, published, created_at, updated_at FROM collections  WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id uuid.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT id, name, image_url, image_id, description, slug, display_order, published, created_at, updated_at FROM collections WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetCollectionBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollections = `-- name: GetCollections :many
SELECT id, name, image_url, image_id, description, slug, display_order, published, created_at, updated_at FROM collections WHERE  published = COALESCE($3, published) ORDER BY display_order LIMIT $1 OFFSET $2
`

type GetCollectionsParams struct {
	Limit     int64 `json:"limit"`
	Offset    int64 `json:"offset"`
	Published *bool `json:"published"`
}

func (q *Queries) GetCollections(ctx context.Context, arg GetCollectionsParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getCollections, arg.Limit, arg.Offset, arg.Published)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.ImageID,
			&i.Description,
			&i.Slug,
			&i.DisplayOrder,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionsByIDs = `-- name: GetCollectionsByIDs :many
SELECT 
    c.id, c.name, c.image_url, c.image_id, c.description, c.slug, c.display_order, c.published, c.created_at, c.updated_at, 
    p.name as product_name, p.id, p.description,
    p.base_price as product_price, 
    p.base_sku as product_sku, p.slug as product_slug
FROM collections AS c
LEFT JOIN collection_products AS cp ON c.id = cp.collection_id
LEFT JOIN products AS p ON cp.product_id = p.id
WHERE c.id = ANY($3::UUID[])
GROUP BY c.id, p.id
LIMIT $1 OFFSET $2
`

type GetCollectionsByIDsParams struct {
	Limit  int64       `json:"limit"`
	Offset int64       `json:"offset"`
	Ids    []uuid.UUID `json:"ids"`
}

type GetCollectionsByIDsRow struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	ImageUrl      *string        `json:"imageUrl"`
	ImageID       *string        `json:"imageId"`
	Description   *string        `json:"description"`
	Slug          string         `json:"slug"`
	DisplayOrder  *int32         `json:"displayOrder"`
	Published     bool           `json:"published"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	ProductName   *string        `json:"productName"`
	ID_2          pgtype.UUID    `json:"id2"`
	Description_2 *string        `json:"description2"`
	ProductPrice  pgtype.Numeric `json:"productPrice"`
	ProductSku    *string        `json:"productSku"`
	ProductSlug   *string        `json:"productSlug"`
}

func (q *Queries) GetCollectionsByIDs(ctx context.Context, arg GetCollectionsByIDsParams) ([]GetCollectionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionsByIDs, arg.Limit, arg.Offset, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionsByIDsRow{}
	for rows.Next() {
		var i GetCollectionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.ImageID,
			&i.Description,
			&i.Slug,
			&i.DisplayOrder,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ID_2,
			&i.Description_2,
			&i.ProductPrice,
			&i.ProductSku,
			&i.ProductSlug,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDisplayCollectionProducts = `-- name: GetDisplayCollectionProducts :many
SELECT 
    p.id, p.name, p.description, p.short_description, p.base_price, p.base_sku, p.slug, p.is_active, p.image_url, p.image_id, p.avg_rating, p.rating_count, p.one_star_count, p.two_star_count, p.three_star_count, p.four_star_count, p.five_star_count, p.created_at, p.updated_at, p.brand_id, COUNT(pv.id) AS variant_count, MIN(pv.price) AS price
FROM collections AS c
JOIN collection_products AS cp ON c.id = cp.collection_id
JOIN products AS p ON cp.product_id = p.id
LEFT JOIN product_variants AS pv ON pv.product_id = p.id
WHERE c.id = $1 AND p.is_active = TRUE
GROUP BY p.id
ORDER BY p.created_at DESC
LIMIT $2 OFFSET $3
`

type GetDisplayCollectionProductsParams struct {
	ID     uuid.UUID `json:"id"`
	Limit  int64     `json:"limit"`
	Offset int64     `json:"offset"`
}

type GetDisplayCollectionProductsRow struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	ShortDescription *string        `json:"shortDescription"`
	BasePrice        pgtype.Numeric `json:"basePrice"`
	BaseSku          string         `json:"baseSku"`
	Slug             string         `json:"slug"`
	IsActive         *bool          `json:"isActive"`
	ImageUrl         *string        `json:"imageUrl"`
	ImageID          *string        `json:"imageId"`
	AvgRating        pgtype.Numeric `json:"avgRating"`
	RatingCount      int32          `json:"ratingCount"`
	OneStarCount     int32          `json:"oneStarCount"`
	TwoStarCount     int32          `json:"twoStarCount"`
	ThreeStarCount   int32          `json:"threeStarCount"`
	FourStarCount    int32          `json:"fourStarCount"`
	FiveStarCount    int32          `json:"fiveStarCount"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	BrandID          pgtype.UUID    `json:"brandId"`
	VariantCount     int64          `json:"variantCount"`
	Price            pgtype.Numeric `json:"price"`
}

func (q *Queries) GetDisplayCollectionProducts(ctx context.Context, arg GetDisplayCollectionProductsParams) ([]GetDisplayCollectionProductsRow, error) {
	rows, err := q.db.Query(ctx, getDisplayCollectionProducts, arg.ID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetDisplayCollectionProductsRow{}
	for rows.Next() {
		var i GetDisplayCollectionProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.ShortDescription,
			&i.BasePrice,
			&i.BaseSku,
			&i.Slug,
			&i.IsActive,
			&i.ImageUrl,
			&i.ImageID,
			&i.AvgRating,
			&i.RatingCount,
			&i.OneStarCount,
			&i.TwoStarCount,
			&i.ThreeStarCount,
			&i.FourStarCount,
			&i.FiveStarCount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BrandID,
			&i.VariantCount,
			&i.Price,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type SeedCollectionsParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ImageUrl    *string `json:"imageUrl"`
}

const updateCollectionWith = `-- name: UpdateCollectionWith :one
UPDATE collections
SET 
    name = COALESCE($2, name), 
    image_url = COALESCE($3, image_url), 
    image_id = COALESCE($4, image_id),
    description = COALESCE($5, description),
    slug = COALESCE($6, slug),
    published = COALESCE($7, published),
    updated_at = now()
WHERE id = $1 RETURNING id, name, image_url, image_id, description, slug, display_order, published, created_at, updated_at
`

type UpdateCollectionWithParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	ImageUrl    *string   `json:"imageUrl"`
	ImageID     *string   `json:"imageId"`
	Description *string   `json:"description"`
	Slug        *string   `json:"slug"`
	Published   *bool     `json:"published"`
}

func (q *Queries) UpdateCollectionWith(ctx context.Context, arg UpdateCollectionWithParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollectionWith,
		arg.ID,
		arg.Name,
		arg.ImageUrl,
		arg.ImageID,
		arg.Description,
		arg.Slug,
		arg.Published,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
