// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: collections.sql

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countCollections = `-- name: CountCollections :one
SELECT count(*) FROM collections
`

func (q *Queries) CountCollections(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countCollections)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCollection = `-- name: CreateCollection :one
INSERT INTO collections (name, slug, description, remarkable, image_url, image_id) VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, name, image_url, image_id, description, slug, remarkable, display_order, published, created_at, updated_at
`

type CreateCollectionParams struct {
	Name        string  `json:"name"`
	Slug        string  `json:"slug"`
	Description *string `json:"description"`
	Remarkable  *bool   `json:"remarkable"`
	ImageUrl    *string `json:"imageUrl"`
	ImageID     *string `json:"imageId"`
}

func (q *Queries) CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error) {
	row := q.db.QueryRow(ctx, createCollection,
		arg.Name,
		arg.Slug,
		arg.Description,
		arg.Remarkable,
		arg.ImageUrl,
		arg.ImageID,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.Remarkable,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCollection = `-- name: DeleteCollection :exec
DELETE FROM collections WHERE id = $1
`

func (q *Queries) DeleteCollection(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCollection, id)
	return err
}

const getCollectionByID = `-- name: GetCollectionByID :one
SELECT c.id, c.name, c.image_url, c.image_id, c.description, c.slug, c.remarkable, c.display_order, c.published, c.created_at, c.updated_at FROM collections c  WHERE c.id = $1 LIMIT 1
`

func (q *Queries) GetCollectionByID(ctx context.Context, id uuid.UUID) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionByID, id)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.Remarkable,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollectionBySlug = `-- name: GetCollectionBySlug :one
SELECT c.id, c.name, c.image_url, c.image_id, c.description, c.slug, c.remarkable, c.display_order, c.published, c.created_at, c.updated_at FROM collections c WHERE c.slug = $1 LIMIT 1
`

func (q *Queries) GetCollectionBySlug(ctx context.Context, slug string) (Collection, error) {
	row := q.db.QueryRow(ctx, getCollectionBySlug, slug)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.Remarkable,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCollections = `-- name: GetCollections :many
SELECT  c.id, c.name, c.image_url, c.image_id, c.description, c.slug, c.remarkable, c.display_order, c.published, c.created_at, c.updated_at FROM collections AS c WHERE  c.published = COALESCE($3, c.published) AND c.remarkable = COALESCE($4, c.remarkable) LIMIT $1 OFFSET $2
`

type GetCollectionsParams struct {
	Limit      int64 `json:"limit"`
	Offset     int64 `json:"offset"`
	Published  *bool `json:"published"`
	Remarkable *bool `json:"remarkable"`
}

func (q *Queries) GetCollections(ctx context.Context, arg GetCollectionsParams) ([]Collection, error) {
	rows, err := q.db.Query(ctx, getCollections,
		arg.Limit,
		arg.Offset,
		arg.Published,
		arg.Remarkable,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Collection{}
	for rows.Next() {
		var i Collection
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.ImageID,
			&i.Description,
			&i.Slug,
			&i.Remarkable,
			&i.DisplayOrder,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCollectionsByIDs = `-- name: GetCollectionsByIDs :many
SELECT 
    c.id, c.name, c.image_url, c.image_id, c.description, c.slug, c.remarkable, c.display_order, c.published, c.created_at, c.updated_at, 
    p.name as product_name, p.id, p.description,
    p.base_price as product_price, 
    p.base_sku as product_sku, p.slug as product_slug,
    pi.id as image_id, pi.image_url
FROM collections AS c
LEFT JOIN products AS p ON c.id = p.collection_id
LEFT JOIN product_images AS pi ON p.id = pi.product_id
WHERE c.id = ANY($3::UUID[])
GROUP BY c.id, p.id, pi.id, pi.image_url
LIMIT $1 OFFSET $2
`

type GetCollectionsByIDsParams struct {
	Limit  int64       `json:"limit"`
	Offset int64       `json:"offset"`
	Ids    []uuid.UUID `json:"ids"`
}

type GetCollectionsByIDsRow struct {
	ID            uuid.UUID      `json:"id"`
	Name          string         `json:"name"`
	ImageUrl      *string        `json:"imageUrl"`
	ImageID       *string        `json:"imageId"`
	Description   *string        `json:"description"`
	Slug          string         `json:"slug"`
	Remarkable    *bool          `json:"remarkable"`
	DisplayOrder  *int32         `json:"displayOrder"`
	Published     bool           `json:"published"`
	CreatedAt     time.Time      `json:"createdAt"`
	UpdatedAt     time.Time      `json:"updatedAt"`
	ProductName   *string        `json:"productName"`
	ID_2          pgtype.UUID    `json:"id2"`
	Description_2 *string        `json:"description2"`
	ProductPrice  pgtype.Numeric `json:"productPrice"`
	ProductSku    *string        `json:"productSku"`
	ProductSlug   *string        `json:"productSlug"`
	ImageID_2     *int64         `json:"imageId2"`
	ImageUrl_2    *string        `json:"imageUrl2"`
}

func (q *Queries) GetCollectionsByIDs(ctx context.Context, arg GetCollectionsByIDsParams) ([]GetCollectionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getCollectionsByIDs, arg.Limit, arg.Offset, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetCollectionsByIDsRow{}
	for rows.Next() {
		var i GetCollectionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ImageUrl,
			&i.ImageID,
			&i.Description,
			&i.Slug,
			&i.Remarkable,
			&i.DisplayOrder,
			&i.Published,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.ID_2,
			&i.Description_2,
			&i.ProductPrice,
			&i.ProductSku,
			&i.ProductSlug,
			&i.ImageID_2,
			&i.ImageUrl_2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type SeedCollectionsParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	ImageUrl    *string `json:"imageUrl"`
}

const updateCollectionWith = `-- name: UpdateCollectionWith :one
UPDATE collections
SET 
    name = COALESCE($2, name), 
    image_url = COALESCE($3, image_url), 
    image_id = COALESCE($4, image_id),
    description = COALESCE($5, description),
    remarkable = COALESCE($6, remarkable),
    slug = COALESCE($7, slug),
    published = COALESCE($8, published),
    updated_at = now()
WHERE id = $1 RETURNING id, name, image_url, image_id, description, slug, remarkable, display_order, published, created_at, updated_at
`

type UpdateCollectionWithParams struct {
	ID          uuid.UUID `json:"id"`
	Name        *string   `json:"name"`
	ImageUrl    *string   `json:"imageUrl"`
	ImageID     *string   `json:"imageId"`
	Description *string   `json:"description"`
	Remarkable  *bool     `json:"remarkable"`
	Slug        *string   `json:"slug"`
	Published   *bool     `json:"published"`
}

func (q *Queries) UpdateCollectionWith(ctx context.Context, arg UpdateCollectionWithParams) (Collection, error) {
	row := q.db.QueryRow(ctx, updateCollectionWith,
		arg.ID,
		arg.Name,
		arg.ImageUrl,
		arg.ImageID,
		arg.Description,
		arg.Remarkable,
		arg.Slug,
		arg.Published,
	)
	var i Collection
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ImageUrl,
		&i.ImageID,
		&i.Description,
		&i.Slug,
		&i.Remarkable,
		&i.DisplayOrder,
		&i.Published,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
