// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: copyfrom.go

package repository

import (
	"context"
)

// iteratorForAddBulkAttributes implements pgx.CopyFromSource.
type iteratorForAddBulkAttributes struct {
	rows                 []string
	skippedFirstNextCall bool
}

func (r *iteratorForAddBulkAttributes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddBulkAttributes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0],
	}, nil
}

func (r iteratorForAddBulkAttributes) Err() error {
	return nil
}

func (q *Queries) AddBulkAttributes(ctx context.Context, name []string) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attributes"}, []string{"name"}, &iteratorForAddBulkAttributes{rows: name})
}

// iteratorForAddBulkProducts implements pgx.CopyFromSource.
type iteratorForAddBulkProducts struct {
	rows                 []AddBulkProductsParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddBulkProducts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddBulkProducts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].BrandID,
		r.rows[0].Name,
		r.rows[0].Description,
	}, nil
}

func (r iteratorForAddBulkProducts) Err() error {
	return nil
}

func (q *Queries) AddBulkProducts(ctx context.Context, arg []AddBulkProductsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"products"}, []string{"brand_id", "name", "description"}, &iteratorForAddBulkProducts{rows: arg})
}

// iteratorForAddProductsToCategory implements pgx.CopyFromSource.
type iteratorForAddProductsToCategory struct {
	rows                 []AddProductsToCategoryParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddProductsToCategory) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddProductsToCategory) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CategoryID,
		r.rows[0].ProductID,
	}, nil
}

func (r iteratorForAddProductsToCategory) Err() error {
	return nil
}

func (q *Queries) AddProductsToCategory(ctx context.Context, arg []AddProductsToCategoryParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"category_products"}, []string{"category_id", "product_id"}, &iteratorForAddProductsToCategory{rows: arg})
}

// iteratorForAddProductsToCollection implements pgx.CopyFromSource.
type iteratorForAddProductsToCollection struct {
	rows                 []AddProductsToCollectionParams
	skippedFirstNextCall bool
}

func (r *iteratorForAddProductsToCollection) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForAddProductsToCollection) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].CollectionID,
		r.rows[0].ProductID,
	}, nil
}

func (r iteratorForAddProductsToCollection) Err() error {
	return nil
}

func (q *Queries) AddProductsToCollection(ctx context.Context, arg []AddProductsToCollectionParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"collection_products"}, []string{"collection_id", "product_id"}, &iteratorForAddProductsToCollection{rows: arg})
}

// iteratorForCreateAttributeValues implements pgx.CopyFromSource.
type iteratorForCreateAttributeValues struct {
	rows                 []CreateAttributeValuesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateAttributeValues) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateAttributeValues) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].AttributeID,
		r.rows[0].Value,
	}, nil
}

func (r iteratorForCreateAttributeValues) Err() error {
	return nil
}

func (q *Queries) CreateAttributeValues(ctx context.Context, arg []CreateAttributeValuesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"attribute_values"}, []string{"attribute_id", "value"}, &iteratorForCreateAttributeValues{rows: arg})
}

// iteratorForCreateBulkOrderItems implements pgx.CopyFromSource.
type iteratorForCreateBulkOrderItems struct {
	rows                 []CreateBulkOrderItemsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBulkOrderItems) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBulkOrderItems) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].OrderID,
		r.rows[0].VariantID,
		r.rows[0].Quantity,
		r.rows[0].PricePerUnitSnapshot,
		r.rows[0].VariantSkuSnapshot,
		r.rows[0].ProductNameSnapshot,
		r.rows[0].LineTotalSnapshot,
		r.rows[0].AttributesSnapshot,
	}, nil
}

func (r iteratorForCreateBulkOrderItems) Err() error {
	return nil
}

func (q *Queries) CreateBulkOrderItems(ctx context.Context, arg []CreateBulkOrderItemsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"order_items"}, []string{"order_id", "variant_id", "quantity", "price_per_unit_snapshot", "variant_sku_snapshot", "product_name_snapshot", "line_total_snapshot", "attributes_snapshot"}, &iteratorForCreateBulkOrderItems{rows: arg})
}

// iteratorForCreateBulkProductAttributes implements pgx.CopyFromSource.
type iteratorForCreateBulkProductAttributes struct {
	rows                 []CreateBulkProductAttributesParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBulkProductAttributes) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBulkProductAttributes) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProductID,
		r.rows[0].AttributeID,
	}, nil
}

func (r iteratorForCreateBulkProductAttributes) Err() error {
	return nil
}

func (q *Queries) CreateBulkProductAttributes(ctx context.Context, arg []CreateBulkProductAttributesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"product_attributes"}, []string{"product_id", "attribute_id"}, &iteratorForCreateBulkProductAttributes{rows: arg})
}

// iteratorForCreateBulkProductVariantAttribute implements pgx.CopyFromSource.
type iteratorForCreateBulkProductVariantAttribute struct {
	rows                 []CreateBulkProductVariantAttributeParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBulkProductVariantAttribute) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBulkProductVariantAttribute) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].VariantID,
		r.rows[0].AttributeValueID,
	}, nil
}

func (r iteratorForCreateBulkProductVariantAttribute) Err() error {
	return nil
}

func (q *Queries) CreateBulkProductVariantAttribute(ctx context.Context, arg []CreateBulkProductVariantAttributeParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"variant_attribute_values"}, []string{"variant_id", "attribute_value_id"}, &iteratorForCreateBulkProductVariantAttribute{rows: arg})
}

// iteratorForCreateBulkProductVariants implements pgx.CopyFromSource.
type iteratorForCreateBulkProductVariants struct {
	rows                 []CreateBulkProductVariantsParams
	skippedFirstNextCall bool
}

func (r *iteratorForCreateBulkProductVariants) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForCreateBulkProductVariants) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProductID,
		r.rows[0].Sku,
		r.rows[0].Price,
		r.rows[0].Stock,
		r.rows[0].Weight,
	}, nil
}

func (r iteratorForCreateBulkProductVariants) Err() error {
	return nil
}

func (q *Queries) CreateBulkProductVariants(ctx context.Context, arg []CreateBulkProductVariantsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"product_variants"}, []string{"product_id", "sku", "price", "stock", "weight"}, &iteratorForCreateBulkProductVariants{rows: arg})
}

// iteratorForInsertBulkProductImages implements pgx.CopyFromSource.
type iteratorForInsertBulkProductImages struct {
	rows                 []InsertBulkProductImagesParams
	skippedFirstNextCall bool
}

func (r *iteratorForInsertBulkProductImages) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForInsertBulkProductImages) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].ProductID,
		r.rows[0].ImageUrl,
		r.rows[0].ImageID,
		r.rows[0].AltText,
		r.rows[0].Caption,
		r.rows[0].DisplayOrder,
	}, nil
}

func (r iteratorForInsertBulkProductImages) Err() error {
	return nil
}

func (q *Queries) InsertBulkProductImages(ctx context.Context, arg []InsertBulkProductImagesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"product_images"}, []string{"product_id", "image_url", "image_id", "alt_text", "caption", "display_order"}, &iteratorForInsertBulkProductImages{rows: arg})
}

// iteratorForSeedAddresses implements pgx.CopyFromSource.
type iteratorForSeedAddresses struct {
	rows                 []SeedAddressesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedAddresses) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedAddresses) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].UserID,
		r.rows[0].PhoneNumber,
		r.rows[0].Street,
		r.rows[0].Ward,
		r.rows[0].District,
		r.rows[0].City,
		r.rows[0].IsDefault,
	}, nil
}

func (r iteratorForSeedAddresses) Err() error {
	return nil
}

func (q *Queries) SeedAddresses(ctx context.Context, arg []SeedAddressesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"user_addresses"}, []string{"user_id", "phone_number", "street", "ward", "district", "city", "is_default"}, &iteratorForSeedAddresses{rows: arg})
}

// iteratorForSeedBrands implements pgx.CopyFromSource.
type iteratorForSeedBrands struct {
	rows                 []SeedBrandsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedBrands) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedBrands) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Slug,
		r.rows[0].Description,
		r.rows[0].DisplayOrder,
		r.rows[0].Published,
	}, nil
}

func (r iteratorForSeedBrands) Err() error {
	return nil
}

func (q *Queries) SeedBrands(ctx context.Context, arg []SeedBrandsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"brands"}, []string{"name", "slug", "description", "display_order", "published"}, &iteratorForSeedBrands{rows: arg})
}

// iteratorForSeedCategories implements pgx.CopyFromSource.
type iteratorForSeedCategories struct {
	rows                 []SeedCategoriesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedCategories) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedCategories) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Slug,
		r.rows[0].Description,
		r.rows[0].ImageUrl,
		r.rows[0].ImageID,
	}, nil
}

func (r iteratorForSeedCategories) Err() error {
	return nil
}

func (q *Queries) SeedCategories(ctx context.Context, arg []SeedCategoriesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"categories"}, []string{"name", "slug", "description", "image_url", "image_id"}, &iteratorForSeedCategories{rows: arg})
}

// iteratorForSeedCollections implements pgx.CopyFromSource.
type iteratorForSeedCollections struct {
	rows                 []SeedCollectionsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedCollections) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedCollections) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].ImageUrl,
		r.rows[0].Slug,
	}, nil
}

func (r iteratorForSeedCollections) Err() error {
	return nil
}

func (q *Queries) SeedCollections(ctx context.Context, arg []SeedCollectionsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"collections"}, []string{"name", "description", "image_url", "slug"}, &iteratorForSeedCollections{rows: arg})
}

// iteratorForSeedDiscounts implements pgx.CopyFromSource.
type iteratorForSeedDiscounts struct {
	rows                 []SeedDiscountsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedDiscounts) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedDiscounts) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Code,
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].DiscountType,
		r.rows[0].DiscountValue,
		r.rows[0].MinOrderValue,
		r.rows[0].MaxDiscountAmount,
		r.rows[0].UsageLimit,
		r.rows[0].UsagePerUser,
		r.rows[0].IsActive,
		r.rows[0].IsStackable,
		r.rows[0].Priority,
		r.rows[0].ValidFrom,
		r.rows[0].ValidUntil,
	}, nil
}

func (r iteratorForSeedDiscounts) Err() error {
	return nil
}

func (q *Queries) SeedDiscounts(ctx context.Context, arg []SeedDiscountsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"discounts"}, []string{"code", "name", "description", "discount_type", "discount_value", "min_order_value", "max_discount_amount", "usage_limit", "usage_per_user", "is_active", "is_stackable", "priority", "valid_from", "valid_until"}, &iteratorForSeedDiscounts{rows: arg})
}

// iteratorForSeedShippingMethods implements pgx.CopyFromSource.
type iteratorForSeedShippingMethods struct {
	rows                 []SeedShippingMethodsParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedShippingMethods) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedShippingMethods) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].IsActive,
		r.rows[0].RequiresAddress,
		r.rows[0].EstimatedDeliveryTime,
	}, nil
}

func (r iteratorForSeedShippingMethods) Err() error {
	return nil
}

func (q *Queries) SeedShippingMethods(ctx context.Context, arg []SeedShippingMethodsParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"shipping_methods"}, []string{"name", "description", "is_active", "requires_address", "estimated_delivery_time"}, &iteratorForSeedShippingMethods{rows: arg})
}

// iteratorForSeedShippingZones implements pgx.CopyFromSource.
type iteratorForSeedShippingZones struct {
	rows                 []SeedShippingZonesParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedShippingZones) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedShippingZones) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Name,
		r.rows[0].Description,
		r.rows[0].Countries,
		r.rows[0].States,
		r.rows[0].ZipCodes,
		r.rows[0].IsActive,
	}, nil
}

func (r iteratorForSeedShippingZones) Err() error {
	return nil
}

func (q *Queries) SeedShippingZones(ctx context.Context, arg []SeedShippingZonesParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"shipping_zones"}, []string{"name", "description", "countries", "states", "zip_codes", "is_active"}, &iteratorForSeedShippingZones{rows: arg})
}

// iteratorForSeedUsers implements pgx.CopyFromSource.
type iteratorForSeedUsers struct {
	rows                 []SeedUsersParams
	skippedFirstNextCall bool
}

func (r *iteratorForSeedUsers) Next() bool {
	if len(r.rows) == 0 {
		return false
	}
	if !r.skippedFirstNextCall {
		r.skippedFirstNextCall = true
		return true
	}
	r.rows = r.rows[1:]
	return len(r.rows) > 0
}

func (r iteratorForSeedUsers) Values() ([]interface{}, error) {
	return []interface{}{
		r.rows[0].Email,
		r.rows[0].Username,
		r.rows[0].PhoneNumber,
		r.rows[0].FirstName,
		r.rows[0].LastName,
		r.rows[0].HashedPassword,
		r.rows[0].RoleID,
	}, nil
}

func (r iteratorForSeedUsers) Err() error {
	return nil
}

func (q *Queries) SeedUsers(ctx context.Context, arg []SeedUsersParams) (int64, error) {
	return q.db.CopyFrom(ctx, []string{"users"}, []string{"email", "username", "phone_number", "first_name", "last_name", "hashed_password", "role_id"}, &iteratorForSeedUsers{rows: arg})
}
