// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"net/netip"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Attribute struct {
	ID        uuid.UUID `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"createdAt"`
}

type AttributeValue struct {
	ID           uuid.UUID `json:"id"`
	AttributeID  uuid.UUID `json:"attributeId"`
	Name         string    `json:"name"`
	Code         string    `json:"code"`
	IsActive     *bool     `json:"isActive"`
	DisplayOrder int16     `json:"displayOrder"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Brand struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	ImageUrl     *string   `json:"imageUrl"`
	ImageID      *string   `json:"imageId"`
	Description  *string   `json:"description"`
	Slug         string    `json:"slug"`
	Remarkable   *bool     `json:"remarkable"`
	DisplayOrder *int32    `json:"displayOrder"`
	Published    bool      `json:"published"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Cart struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"userId"`
	SessionID *string     `json:"sessionId"`
	OrderID   pgtype.UUID `json:"orderId"`
	UpdatedAt time.Time   `json:"updatedAt"`
	CreatedAt time.Time   `json:"createdAt"`
}

type CartItem struct {
	ID        uuid.UUID `json:"id"`
	CartID    uuid.UUID `json:"cartId"`
	VariantID uuid.UUID `json:"variantId"`
	Quantity  int16     `json:"quantity"`
	AddedAt   time.Time `json:"addedAt"`
}

type Category struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	Description  *string   `json:"description"`
	ImageUrl     *string   `json:"imageUrl"`
	ImageID      *string   `json:"imageId"`
	Published    bool      `json:"published"`
	Remarkable   *bool     `json:"remarkable"`
	Slug         string    `json:"slug"`
	DisplayOrder *int32    `json:"displayOrder"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Collection struct {
	ID           uuid.UUID `json:"id"`
	Name         string    `json:"name"`
	ImageUrl     *string   `json:"imageUrl"`
	ImageID      *string   `json:"imageId"`
	Description  *string   `json:"description"`
	Slug         string    `json:"slug"`
	Remarkable   *bool     `json:"remarkable"`
	DisplayOrder *int32    `json:"displayOrder"`
	Published    bool      `json:"published"`
	CreatedAt    time.Time `json:"createdAt"`
	UpdatedAt    time.Time `json:"updatedAt"`
}

type Discount struct {
	ID                uuid.UUID          `json:"id"`
	Code              string             `json:"code"`
	Description       *string            `json:"description"`
	DiscountType      string             `json:"discountType"`
	DiscountValue     pgtype.Numeric     `json:"discountValue"`
	MinPurchaseAmount pgtype.Numeric     `json:"minPurchaseAmount"`
	MaxDiscountAmount pgtype.Numeric     `json:"maxDiscountAmount"`
	UsageLimit        *int32             `json:"usageLimit"`
	UsedCount         int32              `json:"usedCount"`
	IsActive          bool               `json:"isActive"`
	StartsAt          time.Time          `json:"startsAt"`
	ExpiresAt         time.Time          `json:"expiresAt"`
	CreatedAt         time.Time          `json:"createdAt"`
	UpdatedAt         time.Time          `json:"updatedAt"`
	DeletedAt         pgtype.Timestamptz `json:"deletedAt"`
}

type DiscountCategory struct {
	ID         uuid.UUID          `json:"id"`
	DiscountID uuid.UUID          `json:"discountId"`
	CategoryID uuid.UUID          `json:"categoryId"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type DiscountProduct struct {
	ID         uuid.UUID          `json:"id"`
	DiscountID uuid.UUID          `json:"discountId"`
	ProductID  uuid.UUID          `json:"productId"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type DiscountUser struct {
	ID         uuid.UUID          `json:"id"`
	DiscountID uuid.UUID          `json:"discountId"`
	UserID     uuid.UUID          `json:"userId"`
	CreatedAt  pgtype.Timestamptz `json:"createdAt"`
}

type EmailVerification struct {
	ID         uuid.UUID `json:"id"`
	UserID     uuid.UUID `json:"userId"`
	Email      string    `json:"email"`
	VerifyCode string    `json:"verifyCode"`
	IsUsed     bool      `json:"isUsed"`
	CreatedAt  time.Time `json:"createdAt"`
	ExpiredAt  time.Time `json:"expiredAt"`
}

type FeaturedProduct struct {
	ID         uuid.UUID   `json:"id"`
	FeaturedID pgtype.UUID `json:"featuredId"`
	ProductID  pgtype.UUID `json:"productId"`
	SortOrder  int16       `json:"sortOrder"`
}

type FeaturedSection struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Slug        string    `json:"slug"`
	ImageUrl    *string   `json:"imageUrl"`
	ImageID     *string   `json:"imageId"`
	Description *string   `json:"description"`
	Remarkable  *bool     `json:"remarkable"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type Image struct {
	ID         uuid.UUID `json:"id"`
	ExternalID string    `json:"externalId"`
	Url        string    `json:"url"`
	AltText    *string   `json:"altText"`
	Caption    *string   `json:"caption"`
	MimeType   *string   `json:"mimeType"`
	FileSize   *int64    `json:"fileSize"`
	Width      *int32    `json:"width"`
	Height     *int32    `json:"height"`
	UploadedAt time.Time `json:"uploadedAt"`
	UpdatedAt  time.Time `json:"updatedAt"`
}

type ImageAssignment struct {
	ID           uuid.UUID `json:"id"`
	ImageID      uuid.UUID `json:"imageId"`
	EntityID     uuid.UUID `json:"entityId"`
	EntityType   string    `json:"entityType"`
	DisplayOrder int16     `json:"displayOrder"`
	Role         string    `json:"role"`
	CreatedAt    time.Time `json:"createdAt"`
}

type Order struct {
	ID                    uuid.UUID               `json:"id"`
	CustomerID            uuid.UUID               `json:"customerId"`
	CustomerEmail         string                  `json:"customerEmail"`
	CustomerName          string                  `json:"customerName"`
	CustomerPhone         string                  `json:"customerPhone"`
	ShippingAddress       ShippingAddressSnapshot `json:"shippingAddress"`
	TotalPrice            pgtype.Numeric          `json:"totalPrice"`
	Status                OrderStatus             `json:"status"`
	ConfirmedAt           pgtype.Timestamptz      `json:"confirmedAt"`
	DeliveredAt           pgtype.Timestamptz      `json:"deliveredAt"`
	CancelledAt           pgtype.Timestamptz      `json:"cancelledAt"`
	ShippingMethod        *string                 `json:"shippingMethod"`
	RefundedAt            pgtype.Timestamptz      `json:"refundedAt"`
	OrderDate             time.Time               `json:"orderDate"`
	UpdatedAt             time.Time               `json:"updatedAt"`
	CreatedAt             time.Time               `json:"createdAt"`
	ShippingMethodID      pgtype.UUID             `json:"shippingMethodId"`
	ShippingRateID        pgtype.UUID             `json:"shippingRateId"`
	EstimatedDeliveryDate pgtype.Timestamptz      `json:"estimatedDeliveryDate"`
	TrackingUrl           *string                 `json:"trackingUrl"`
	ShippingProvider      *string                 `json:"shippingProvider"`
	ShippingNotes         *string                 `json:"shippingNotes"`
}

type OrderDiscount struct {
	ID             uuid.UUID          `json:"id"`
	OrderID        uuid.UUID          `json:"orderId"`
	DiscountID     uuid.UUID          `json:"discountId"`
	DiscountAmount pgtype.Numeric     `json:"discountAmount"`
	CreatedAt      pgtype.Timestamptz `json:"createdAt"`
}

type OrderItem struct {
	ID                   uuid.UUID               `json:"id"`
	OrderID              uuid.UUID               `json:"orderId"`
	VariantID            uuid.UUID               `json:"variantId"`
	Quantity             int16                   `json:"quantity"`
	PricePerUnitSnapshot pgtype.Numeric          `json:"pricePerUnitSnapshot"`
	LineTotalSnapshot    pgtype.Numeric          `json:"lineTotalSnapshot"`
	ProductNameSnapshot  string                  `json:"productNameSnapshot"`
	VariantSkuSnapshot   string                  `json:"variantSkuSnapshot"`
	AttributesSnapshot   []AttributeDataSnapshot `json:"attributesSnapshot"`
	CreatedAt            time.Time               `json:"createdAt"`
	UpdatedAt            time.Time               `json:"updatedAt"`
	DiscountedPrice      pgtype.Numeric          `json:"discountedPrice"`
}

type Payment struct {
	ID              uuid.UUID          `json:"id"`
	OrderID         uuid.UUID          `json:"orderId"`
	Amount          pgtype.Numeric     `json:"amount"`
	Status          PaymentStatus      `json:"status"`
	Method          PaymentMethod      `json:"method"`
	Gateway         *string            `json:"gateway"`
	RefundID        *string            `json:"refundId"`
	PaymentIntentID *string            `json:"paymentIntentId"`
	ChargeID        *string            `json:"chargeId"`
	ErrorCode       *string            `json:"errorCode"`
	ErrorMessage    *string            `json:"errorMessage"`
	CreatedAt       pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt       pgtype.Timestamptz `json:"updatedAt"`
}

type PaymentTransaction struct {
	ID                     uuid.UUID          `json:"id"`
	PaymentID              uuid.UUID          `json:"paymentId"`
	Amount                 pgtype.Numeric     `json:"amount"`
	Status                 PaymentStatus      `json:"status"`
	GatewayTransactionID   *string            `json:"gatewayTransactionId"`
	GatewayResponseCode    *string            `json:"gatewayResponseCode"`
	GatewayResponseMessage *string            `json:"gatewayResponseMessage"`
	TransactionDate        pgtype.Timestamptz `json:"transactionDate"`
	CreatedAt              pgtype.Timestamptz `json:"createdAt"`
}

type Product struct {
	ID               uuid.UUID      `json:"id"`
	Name             string         `json:"name"`
	Description      string         `json:"description"`
	ShortDescription *string        `json:"shortDescription"`
	Attributes       []uuid.UUID    `json:"attributes"`
	BasePrice        pgtype.Numeric `json:"basePrice"`
	BaseSku          string         `json:"baseSku"`
	Slug             string         `json:"slug"`
	IsActive         *bool          `json:"isActive"`
	CategoryID       pgtype.UUID    `json:"categoryId"`
	CollectionID     pgtype.UUID    `json:"collectionId"`
	BrandID          pgtype.UUID    `json:"brandId"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
	AvgRating        pgtype.Numeric `json:"avgRating"`
	RatingCount      int32          `json:"ratingCount"`
	OneStarCount     int32          `json:"oneStarCount"`
	TwoStarCount     int32          `json:"twoStarCount"`
	ThreeStarCount   int32          `json:"threeStarCount"`
	FourStarCount    int32          `json:"fourStarCount"`
	FiveStarCount    int32          `json:"fiveStarCount"`
}

type ProductRating struct {
	ID               uuid.UUID      `json:"id"`
	ProductID        uuid.UUID      `json:"productId"`
	UserID           uuid.UUID      `json:"userId"`
	OrderItemID      pgtype.UUID    `json:"orderItemId"`
	Rating           pgtype.Numeric `json:"rating"`
	ReviewTitle      *string        `json:"reviewTitle"`
	ReviewContent    *string        `json:"reviewContent"`
	VerifiedPurchase bool           `json:"verifiedPurchase"`
	IsVisible        bool           `json:"isVisible"`
	IsApproved       bool           `json:"isApproved"`
	CreatedAt        time.Time      `json:"createdAt"`
	UpdatedAt        time.Time      `json:"updatedAt"`
}

type ProductVariant struct {
	ID          uuid.UUID      `json:"id"`
	ProductID   uuid.UUID      `json:"productId"`
	Description *string        `json:"description"`
	Sku         string         `json:"sku"`
	Price       pgtype.Numeric `json:"price"`
	Stock       int32          `json:"stock"`
	Weight      pgtype.Numeric `json:"weight"`
	IsActive    *bool          `json:"isActive"`
	CreatedAt   time.Time      `json:"createdAt"`
	UpdatedAt   time.Time      `json:"updatedAt"`
}

type RatingReply struct {
	ID        uuid.UUID `json:"id"`
	RatingID  uuid.UUID `json:"ratingId"`
	ReplyBy   uuid.UUID `json:"replyBy"`
	Content   string    `json:"content"`
	IsVisible bool      `json:"isVisible"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type RatingVote struct {
	ID        uuid.UUID `json:"id"`
	RatingID  uuid.UUID `json:"ratingId"`
	UserID    uuid.UUID `json:"userId"`
	IsHelpful bool      `json:"isHelpful"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}

type Shipment struct {
	ID               uuid.UUID          `json:"id"`
	OrderID          uuid.UUID          `json:"orderId"`
	Status           string             `json:"status"`
	ShippedAt        pgtype.Timestamptz `json:"shippedAt"`
	DeliveredAt      pgtype.Timestamptz `json:"deliveredAt"`
	TrackingNumber   *string            `json:"trackingNumber"`
	TrackingUrl      *string            `json:"trackingUrl"`
	ShippingProvider *string            `json:"shippingProvider"`
	ShippingNotes    *string            `json:"shippingNotes"`
	CreatedAt        time.Time          `json:"createdAt"`
	UpdatedAt        time.Time          `json:"updatedAt"`
}

type ShipmentItem struct {
	ShipmentID  uuid.UUID `json:"shipmentId"`
	OrderItemID uuid.UUID `json:"orderItemId"`
	Quantity    int32     `json:"quantity"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type ShippingMethod struct {
	ID                    uuid.UUID `json:"id"`
	Name                  string    `json:"name"`
	Description           *string   `json:"description"`
	IsActive              bool      `json:"isActive"`
	RequiresAddress       bool      `json:"requiresAddress"`
	EstimatedDeliveryTime *string   `json:"estimatedDeliveryTime"`
	IconUrl               *string   `json:"iconUrl"`
	CreatedAt             time.Time `json:"createdAt"`
	UpdatedAt             time.Time `json:"updatedAt"`
}

type ShippingRate struct {
	ID                    uuid.UUID      `json:"id"`
	ShippingMethodID      uuid.UUID      `json:"shippingMethodId"`
	ShippingZoneID        uuid.UUID      `json:"shippingZoneId"`
	Name                  string         `json:"name"`
	BaseRate              pgtype.Numeric `json:"baseRate"`
	MinOrderAmount        pgtype.Numeric `json:"minOrderAmount"`
	MaxOrderAmount        pgtype.Numeric `json:"maxOrderAmount"`
	FreeShippingThreshold pgtype.Numeric `json:"freeShippingThreshold"`
	IsActive              bool           `json:"isActive"`
	CreatedAt             time.Time      `json:"createdAt"`
	UpdatedAt             time.Time      `json:"updatedAt"`
}

type ShippingRateCondition struct {
	ID             uuid.UUID      `json:"id"`
	ShippingRateID uuid.UUID      `json:"shippingRateId"`
	ConditionType  string         `json:"conditionType"`
	MinValue       pgtype.Numeric `json:"minValue"`
	MaxValue       pgtype.Numeric `json:"maxValue"`
	AdditionalFee  pgtype.Numeric `json:"additionalFee"`
	CategoryIds    []uuid.UUID    `json:"categoryIds"`
	CreatedAt      time.Time      `json:"createdAt"`
	UpdatedAt      time.Time      `json:"updatedAt"`
}

type ShippingZone struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Countries   []string  `json:"countries"`
	States      []string  `json:"states"`
	ZipCodes    []string  `json:"zipCodes"`
	IsActive    bool      `json:"isActive"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type User struct {
	ID                uuid.UUID `json:"id"`
	Role              UserRole  `json:"role"`
	Username          string    `json:"username"`
	Email             string    `json:"email"`
	PhoneNumber       string    `json:"phoneNumber"`
	FirstName         string    `json:"firstName"`
	LastName          string    `json:"lastName"`
	AvatarUrl         *string   `json:"avatarUrl"`
	AvatarImageID     *string   `json:"avatarImageId"`
	HashedPassword    string    `json:"hashedPassword"`
	VerifiedEmail     bool      `json:"verifiedEmail"`
	VerifiedPhone     bool      `json:"verifiedPhone"`
	Locked            bool      `json:"locked"`
	PasswordChangedAt time.Time `json:"passwordChangedAt"`
	UpdatedAt         time.Time `json:"updatedAt"`
	CreatedAt         time.Time `json:"createdAt"`
}

type UserAddress struct {
	ID          uuid.UUID `json:"id"`
	UserID      uuid.UUID `json:"userId"`
	PhoneNumber string    `json:"phoneNumber"`
	Street      string    `json:"street"`
	Ward        *string   `json:"ward"`
	District    string    `json:"district"`
	City        string    `json:"city"`
	Default     bool      `json:"default"`
	CreatedAt   time.Time `json:"createdAt"`
	UpdatedAt   time.Time `json:"updatedAt"`
}

type UserPaymentInfo struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"userId"`
	CardNumber         string             `json:"cardNumber"`
	CardLast4          string             `json:"cardLast4"`
	PaymentMethodToken string             `json:"paymentMethodToken"`
	ExpirationDate     pgtype.Date        `json:"expirationDate"`
	BillingAddress     string             `json:"billingAddress"`
	Default            *bool              `json:"default"`
	CreatedAt          pgtype.Timestamptz `json:"createdAt"`
	UpdatedAt          pgtype.Timestamptz `json:"updatedAt"`
}

type UserSession struct {
	ID           uuid.UUID  `json:"id"`
	UserID       uuid.UUID  `json:"userId"`
	RefreshToken string     `json:"refreshToken"`
	UserAgent    string     `json:"userAgent"`
	ClientIp     netip.Addr `json:"clientIp"`
	Blocked      bool       `json:"blocked"`
	ExpiredAt    time.Time  `json:"expiredAt"`
	CreatedAt    time.Time  `json:"createdAt"`
}

type VariantAttributeValue struct {
	VariantID        uuid.UUID `json:"variantId"`
	AttributeValueID uuid.UUID `json:"attributeValueId"`
}
