// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: payments.sql

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPayment = `-- name: CreatePayment :one
INSERT INTO payments (order_id,amount,payment_method_id,gateway,status,payment_intent_id,charge_id) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING id, order_id, payment_method_id, amount, processing_fee, net_amount, status, gateway, gateway_reference, refund_id, payment_intent_id, charge_id, error_code, error_message, metadata, created_at, updated_at
`

type CreatePaymentParams struct {
	OrderID         uuid.UUID      `json:"orderId"`
	Amount          pgtype.Numeric `json:"amount"`
	PaymentMethodID uuid.UUID      `json:"paymentMethodId"`
	Gateway         *string        `json:"gateway"`
	Status          PaymentStatus  `json:"status"`
	PaymentIntentID *string        `json:"paymentIntentId"`
	ChargeID        *string        `json:"chargeId"`
}

func (q *Queries) CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, createPayment,
		arg.OrderID,
		arg.Amount,
		arg.PaymentMethodID,
		arg.Gateway,
		arg.Status,
		arg.PaymentIntentID,
		arg.ChargeID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.ProcessingFee,
		&i.NetAmount,
		&i.Status,
		&i.Gateway,
		&i.GatewayReference,
		&i.RefundID,
		&i.PaymentIntentID,
		&i.ChargeID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPaymentTransaction = `-- name: CreatePaymentTransaction :one
INSERT INTO payment_transactions (payment_id,amount,status,gateway_transaction_id,gateway_response_code,gateway_response_message) VALUES ($1,$2,$3,$4,$5,$6) RETURNING id, payment_id, amount, status, gateway_transaction_id, gateway_response_code, gateway_response_message, transaction_date, created_at
`

type CreatePaymentTransactionParams struct {
	PaymentID              uuid.UUID      `json:"paymentId"`
	Amount                 pgtype.Numeric `json:"amount"`
	Status                 PaymentStatus  `json:"status"`
	GatewayTransactionID   *string        `json:"gatewayTransactionId"`
	GatewayResponseCode    *string        `json:"gatewayResponseCode"`
	GatewayResponseMessage *string        `json:"gatewayResponseMessage"`
}

// Payment Transactions --
func (q *Queries) CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, createPaymentTransaction,
		arg.PaymentID,
		arg.Amount,
		arg.Status,
		arg.GatewayTransactionID,
		arg.GatewayResponseCode,
		arg.GatewayResponseMessage,
	)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.Status,
		&i.GatewayTransactionID,
		&i.GatewayResponseCode,
		&i.GatewayResponseMessage,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const deletePayment = `-- name: DeletePayment :exec
DELETE FROM payments WHERE id = $1
`

func (q *Queries) DeletePayment(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePayment, id)
	return err
}

const deletePaymentTransaction = `-- name: DeletePaymentTransaction :exec
DELETE FROM payment_transactions WHERE id = $1
`

func (q *Queries) DeletePaymentTransaction(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deletePaymentTransaction, id)
	return err
}

const getPaymentByID = `-- name: GetPaymentByID :one
SELECT id, order_id, payment_method_id, amount, processing_fee, net_amount, status, gateway, gateway_reference, refund_id, payment_intent_id, charge_id, error_code, error_message, metadata, created_at, updated_at FROM payments WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByID, id)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.ProcessingFee,
		&i.NetAmount,
		&i.Status,
		&i.Gateway,
		&i.GatewayReference,
		&i.RefundID,
		&i.PaymentIntentID,
		&i.ChargeID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByOrderID = `-- name: GetPaymentByOrderID :one
SELECT id, order_id, payment_method_id, amount, processing_fee, net_amount, status, gateway, gateway_reference, refund_id, payment_intent_id, charge_id, error_code, error_message, metadata, created_at, updated_at FROM payments WHERE order_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByOrderID, orderID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.ProcessingFee,
		&i.NetAmount,
		&i.Status,
		&i.Gateway,
		&i.GatewayReference,
		&i.RefundID,
		&i.PaymentIntentID,
		&i.ChargeID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentByPaymentIntentID = `-- name: GetPaymentByPaymentIntentID :one
SELECT id, order_id, payment_method_id, amount, processing_fee, net_amount, status, gateway, gateway_reference, refund_id, payment_intent_id, charge_id, error_code, error_message, metadata, created_at, updated_at FROM payments WHERE payment_intent_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByPaymentIntentID(ctx context.Context, paymentIntentID *string) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByPaymentIntentID, paymentIntentID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.PaymentMethodID,
		&i.Amount,
		&i.ProcessingFee,
		&i.NetAmount,
		&i.Status,
		&i.Gateway,
		&i.GatewayReference,
		&i.RefundID,
		&i.PaymentIntentID,
		&i.ChargeID,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentMethodByID = `-- name: GetPaymentMethodByID :one
SELECT id, code, name, description, is_active, gateway_supported, icon_url, display_order, requires_account, min_amount, max_amount, processing_fee_percentage, processing_fee_fixed, currency_supported, countries_supported, metadata, created_at, updated_at FROM payment_methods WHERE id = $1 LIMIT 1
`

// Payment Methods --
func (q *Queries) GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (PaymentMethod, error) {
	row := q.db.QueryRow(ctx, getPaymentMethodByID, id)
	var i PaymentMethod
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Description,
		&i.IsActive,
		&i.GatewaySupported,
		&i.IconUrl,
		&i.DisplayOrder,
		&i.RequiresAccount,
		&i.MinAmount,
		&i.MaxAmount,
		&i.ProcessingFeePercentage,
		&i.ProcessingFeeFixed,
		&i.CurrencySupported,
		&i.CountriesSupported,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPaymentTransactionByID = `-- name: GetPaymentTransactionByID :one
SELECT id, payment_id, amount, status, gateway_transaction_id, gateway_response_code, gateway_response_message, transaction_date, created_at FROM payment_transactions WHERE id = $1 LIMIT 1
`

func (q *Queries) GetPaymentTransactionByID(ctx context.Context, id uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getPaymentTransactionByID, id)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.Status,
		&i.GatewayTransactionID,
		&i.GatewayResponseCode,
		&i.GatewayResponseMessage,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentTransactionByPaymentID = `-- name: GetPaymentTransactionByPaymentID :one
SELECT id, payment_id, amount, status, gateway_transaction_id, gateway_response_code, gateway_response_message, transaction_date, created_at FROM payment_transactions WHERE payment_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentTransactionByPaymentID(ctx context.Context, paymentID uuid.UUID) (PaymentTransaction, error) {
	row := q.db.QueryRow(ctx, getPaymentTransactionByPaymentID, paymentID)
	var i PaymentTransaction
	err := row.Scan(
		&i.ID,
		&i.PaymentID,
		&i.Amount,
		&i.Status,
		&i.GatewayTransactionID,
		&i.GatewayResponseCode,
		&i.GatewayResponseMessage,
		&i.TransactionDate,
		&i.CreatedAt,
	)
	return i, err
}

const updatePayment = `-- name: UpdatePayment :exec
UPDATE
    payments
SET
    amount = COALESCE($2, amount),
    refund_id = COALESCE($3, refund_id),
    status = COALESCE($4, status),
    gateway = COALESCE($5, gateway),
    payment_intent_id = COALESCE($6, payment_intent_id),
    charge_id = COALESCE($7, charge_id),
    error_code = COALESCE($8, error_code),
    error_message = COALESCE($9, error_message),
    updated_at = NOW()
WHERE id = $1
`

type UpdatePaymentParams struct {
	ID              uuid.UUID      `json:"id"`
	Amount          pgtype.Numeric `json:"amount"`
	RefundID        *string        `json:"refundId"`
	Status          interface{}    `json:"status"`
	Gateway         *string        `json:"gateway"`
	PaymentIntentID *string        `json:"paymentIntentId"`
	ChargeID        *string        `json:"chargeId"`
	ErrorCode       *string        `json:"errorCode"`
	ErrorMessage    *string        `json:"errorMessage"`
}

func (q *Queries) UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error {
	_, err := q.db.Exec(ctx, updatePayment,
		arg.ID,
		arg.Amount,
		arg.RefundID,
		arg.Status,
		arg.Gateway,
		arg.PaymentIntentID,
		arg.ChargeID,
		arg.ErrorCode,
		arg.ErrorMessage,
	)
	return err
}

const updatePaymentTransaction = `-- name: UpdatePaymentTransaction :exec
UPDATE payment_transactions
SET
    amount = COALESCE($2, amount),
    status = COALESCE($3, status),
    gateway_transaction_id = COALESCE($4, gateway_transaction_id),
    gateway_response_code = COALESCE($5, gateway_response_code),
    gateway_response_message = COALESCE($6, gateway_response_message)
WHERE id = $1
`

type UpdatePaymentTransactionParams struct {
	ID                     uuid.UUID      `json:"id"`
	Amount                 pgtype.Numeric `json:"amount"`
	Status                 interface{}    `json:"status"`
	GatewayTransactionID   *string        `json:"gatewayTransactionId"`
	GatewayResponseCode    *string        `json:"gatewayResponseCode"`
	GatewayResponseMessage *string        `json:"gatewayResponseMessage"`
}

func (q *Queries) UpdatePaymentTransaction(ctx context.Context, arg UpdatePaymentTransactionParams) error {
	_, err := q.db.Exec(ctx, updatePaymentTransaction,
		arg.ID,
		arg.Amount,
		arg.Status,
		arg.GatewayTransactionID,
		arg.GatewayResponseCode,
		arg.GatewayResponseMessage,
	)
	return err
}
