// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddBulkAttributes(ctx context.Context, name []string) (int64, error)
	AddBulkProducts(ctx context.Context, arg []AddBulkProductsParams) (int64, error)
	// Cart Item Section
	AddCartItem(ctx context.Context, arg AddCartItemParams) (CartItem, error)
	AddDiscountRule(ctx context.Context, arg AddDiscountRuleParams) (DiscountRule, error)
	AddDiscountUsage(ctx context.Context, arg AddDiscountUsageParams) (DiscountUsage, error)
	AddProductsToCategory(ctx context.Context, arg []AddProductsToCategoryParams) (int64, error)
	AddProductsToCollection(ctx context.Context, arg []AddProductsToCollectionParams) (int64, error)
	ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error
	ArchiveProductVariant(ctx context.Context, arg ArchiveProductVariantParams) error
	CheckoutCart(ctx context.Context, arg CheckoutCartParams) error
	ClearCart(ctx context.Context, id uuid.UUID) error
	CountAddresses(ctx context.Context) (int64, error)
	CountAttributes(ctx context.Context) (int64, error)
	CountAvailableDiscountsForUser(ctx context.Context, userID uuid.UUID) (int64, error)
	CountBrands(ctx context.Context) (int64, error)
	CountCartItems(ctx context.Context, id uuid.UUID) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountCollections(ctx context.Context) (int64, error)
	CountDiscountRules(ctx context.Context, discountID uuid.UUID) (int64, error)
	CountDiscountRulesByType(ctx context.Context, arg CountDiscountRulesByTypeParams) (int64, error)
	CountDiscountUsageByDiscountAndUser(ctx context.Context, arg CountDiscountUsageByDiscountAndUserParams) (int64, error)
	CountDiscountUsages(ctx context.Context, discountID uuid.UUID) (int64, error)
	CountDiscounts(ctx context.Context) (int64, error)
	CountDiscountsByPriority(ctx context.Context, priority *int32) (int64, error)
	CountDiscountsByType(ctx context.Context, discountType DiscountType) (int64, error)
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CountProductRatings(ctx context.Context, productID pgtype.UUID) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountShippingMethods(ctx context.Context) (int64, error)
	CountShippingRates(ctx context.Context) (int64, error)
	CountShippingZones(ctx context.Context) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	CountUsersUsingDiscount(ctx context.Context, discountID uuid.UUID) (int64, error)
	// User Address Queries
	CreateAddress(ctx context.Context, arg CreateAddressParams) (UserAddress, error)
	CreateAttribute(ctx context.Context, name string) (Attribute, error)
	// Attribute values
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error)
	CreateAttributeValues(ctx context.Context, arg []CreateAttributeValuesParams) (int64, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateBulkOrderItems(ctx context.Context, arg []CreateBulkOrderItemsParams) (int64, error)
	CreateBulkProductAttributes(ctx context.Context, arg []CreateBulkProductAttributesParams) (int64, error)
	CreateBulkProductVariantAttribute(ctx context.Context, arg []CreateBulkProductVariantAttributeParams) (int64, error)
	CreateBulkProductVariants(ctx context.Context, arg []CreateBulkProductVariantsParams) (int64, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Payment Transactions --
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	// PRODUCT ATTRIBUTES QUERIES
	CreateProductAttribute(ctx context.Context, arg CreateProductAttributeParams) (ProductAttribute, error)
	// Product Variants --
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	// Product Variant attributes
	CreateProductVariantAttribute(ctx context.Context, arg CreateProductVariantAttributeParams) (VariantAttributeValue, error)
	CreateShippingMethod(ctx context.Context, arg CreateShippingMethodParams) (ShippingMethod, error)
	// SHIPPING RATES
	CreateShippingRate(ctx context.Context, arg CreateShippingRateParams) (ShippingRate, error)
	// SHIPPING ZONES
	CreateShippingZone(ctx context.Context, arg CreateShippingZoneParams) (ShippingZone, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Verification Token Queries
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (EmailVerification, error)
	DeactivateDiscount(ctx context.Context, id uuid.UUID) error
	DecrementDiscountUsage(ctx context.Context, id uuid.UUID) error
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteAttribute(ctx context.Context, id int32) error
	DeleteAttributeValue(ctx context.Context, id int64) error
	DeleteAttributeValueByValueID(ctx context.Context, arg DeleteAttributeValueByValueIDParams) error
	DeleteBrand(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCollection(ctx context.Context, id uuid.UUID) error
	DeleteDiscount(ctx context.Context, id uuid.UUID) error
	DeleteDiscountRule(ctx context.Context, id uuid.UUID) error
	DeleteDiscountRules(ctx context.Context, discountID uuid.UUID) error
	DeleteDiscountRulesByType(ctx context.Context, arg DeleteDiscountRulesByTypeParams) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	DeletePayment(ctx context.Context, id uuid.UUID) error
	DeletePaymentTransaction(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductAttributesByProductID(ctx context.Context, productID uuid.UUID) error
	DeleteProductImage(ctx context.Context, id int64) error
	DeleteProductImagesByProductID(ctx context.Context, productID uuid.UUID) error
	DeleteProductRating(ctx context.Context, id uuid.UUID) error
	DeleteProductVariant(ctx context.Context, arg DeleteProductVariantParams) error
	DeleteProductVariantAttributes(ctx context.Context, variantID uuid.UUID) error
	DeleteRatingReplies(ctx context.Context, id uuid.UUID) error
	DeleteRatingVotes(ctx context.Context, id uuid.UUID) error
	DeleteShippingMethod(ctx context.Context, id uuid.UUID) error
	DeleteShippingRate(ctx context.Context, id uuid.UUID) error
	DeleteShippingZone(ctx context.Context, id uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetActiveDiscountRules(ctx context.Context, arg GetActiveDiscountRulesParams) ([]DiscountRule, error)
	GetActiveDiscounts(ctx context.Context) ([]Discount, error)
	GetAddress(ctx context.Context, arg GetAddressParams) (UserAddress, error)
	GetAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error)
	GetAdminProductList(ctx context.Context, arg GetAdminProductListParams) ([]Product, error)
	GetAttributeByID(ctx context.Context, id int32) (Attribute, error)
	GetAttributeByName(ctx context.Context, name string) (Attribute, error)
	GetAttributeValueByID(ctx context.Context, id int64) (AttributeValue, error)
	GetAttributeValues(ctx context.Context, attributeID int32) ([]AttributeValue, error)
	GetAttributeValuesByIDs(ctx context.Context, ids []int64) ([]AttributeValue, error)
	GetAttributeWithValuesByIDs(ctx context.Context, ids []int32) ([]GetAttributeWithValuesByIDsRow, error)
	GetAttributes(ctx context.Context, ids []int32) ([]GetAttributesRow, error)
	GetAttributesByIDs(ctx context.Context, ids []int32) ([]Attribute, error)
	GetAvailableDiscountsForUser(ctx context.Context, userID uuid.UUID) ([]Discount, error)
	GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error)
	GetBrandBySlug(ctx context.Context, slug string) (Brand, error)
	GetBrands(ctx context.Context, arg GetBrandsParams) ([]Brand, error)
	GetBrandsByIDs(ctx context.Context, arg GetBrandsByIDsParams) ([]GetBrandsByIDsRow, error)
	GetCart(ctx context.Context, arg GetCartParams) (GetCartRow, error)
	GetCartDetails(ctx context.Context, id uuid.UUID) (GetCartDetailsRow, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error)
	GetCartItemByProductVariantID(ctx context.Context, arg GetCartItemByProductVariantIDParams) (CartItem, error)
	GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCollectionByID(ctx context.Context, id uuid.UUID) (Collection, error)
	GetCollectionBySlug(ctx context.Context, slug string) (Collection, error)
	GetCollections(ctx context.Context, arg GetCollectionsParams) ([]Collection, error)
	GetCollectionsByIDs(ctx context.Context, arg GetCollectionsByIDsParams) ([]GetCollectionsByIDsRow, error)
	GetDefaultAddress(ctx context.Context, userID uuid.UUID) (UserAddress, error)
	GetDiscountByCode(ctx context.Context, code string) (GetDiscountByCodeRow, error)
	GetDiscountByCodes(ctx context.Context, code []string) ([]Discount, error)
	GetDiscountByID(ctx context.Context, id uuid.UUID) (Discount, error)
	GetDiscountRuleByID(ctx context.Context, id uuid.UUID) (DiscountRule, error)
	GetDiscountRules(ctx context.Context, discountID uuid.UUID) ([]DiscountRule, error)
	GetDiscountUsages(ctx context.Context, id uuid.UUID) ([]GetDiscountUsagesRow, error)
	GetDiscountUsagesByUser(ctx context.Context, arg GetDiscountUsagesByUserParams) ([]GetDiscountUsagesByUserRow, error)
	GetDiscounts(ctx context.Context, arg GetDiscountsParams) ([]Discount, error)
	GetDiscountsByPriority(ctx context.Context, arg GetDiscountsByPriorityParams) ([]Discount, error)
	GetDiscountsByType(ctx context.Context, arg GetDiscountsByTypeParams) ([]Discount, error)
	GetDiscountsWithRules(ctx context.Context, arg GetDiscountsWithRulesParams) ([]GetDiscountsWithRulesRow, error)
	GetDiscountsWithUsageStatsByUserId(ctx context.Context, arg GetDiscountsWithUsageStatsByUserIdParams) ([]GetDiscountsWithUsageStatsByUserIdRow, error)
	GetExpiredDiscounts(ctx context.Context) ([]Discount, error)
	GetImageByID(ctx context.Context, id int64) (ProductImage, error)
	GetImageByImageID(ctx context.Context, imageID string) (ProductImage, error)
	GetImagesByProductID(ctx context.Context, productID uuid.UUID) ([]ProductImage, error)
	GetOrder(ctx context.Context, id uuid.UUID) (GetOrderRow, error)
	GetOrderItemByID(ctx context.Context, id uuid.UUID) (GetOrderItemByIDRow, error)
	GetOrderItems(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsRow, error)
	GetOrderItemsByOrderID(ctx context.Context, orderID uuid.UUID) ([]GetOrderItemsByOrderIDRow, error)
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]GetOrdersRow, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error)
	GetPaymentByPaymentIntentID(ctx context.Context, paymentIntentID *string) (Payment, error)
	// Payment Methods --
	GetPaymentMethodByID(ctx context.Context, id uuid.UUID) (PaymentMethod, error)
	GetPaymentMethods(ctx context.Context) ([]PaymentMethod, error)
	GetPaymentTransactionByID(ctx context.Context, id uuid.UUID) (PaymentTransaction, error)
	GetPaymentTransactionByPaymentID(ctx context.Context, paymentID uuid.UUID) (PaymentTransaction, error)
	GetPrimaryImageByProductID(ctx context.Context, productID uuid.UUID) (ProductImage, error)
	GetProductAttributeValuesByProductID(ctx context.Context, productID uuid.UUID) ([]GetProductAttributeValuesByProductIDRow, error)
	GetProductAttributesByProductID(ctx context.Context, productID uuid.UUID) ([]GetProductAttributesByProductIDRow, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetProductBySku(ctx context.Context, arg GetProductBySkuParams) (Product, error)
	GetProductBySlug(ctx context.Context, arg GetProductBySlugParams) (Product, error)
	GetProductDetail(ctx context.Context, arg GetProductDetailParams) (GetProductDetailRow, error)
	GetProductImages(ctx context.Context, productIds []uuid.UUID) ([]GetProductImagesRow, error)
	GetProductList(ctx context.Context, arg GetProductListParams) ([]GetProductListRow, error)
	GetProductRating(ctx context.Context, id uuid.UUID) (ProductRating, error)
	GetProductRatings(ctx context.Context, arg GetProductRatingsParams) ([]GetProductRatingsRow, error)
	GetProductRatingsByOrderItemIDs(ctx context.Context, ids []uuid.UUID) ([]GetProductRatingsByOrderItemIDsRow, error)
	GetProductRatingsByUserID(ctx context.Context, arg GetProductRatingsByUserIDParams) ([]GetProductRatingsByUserIDRow, error)
	GetProductRatingsCount(ctx context.Context, productID uuid.UUID) (int64, error)
	GetProductVariantAttributeByID(ctx context.Context, variantID uuid.UUID) (VariantAttributeValue, error)
	GetProductVariantAttributes(ctx context.Context, variantID uuid.UUID) ([]VariantAttributeValue, error)
	GetProductVariantByID(ctx context.Context, arg GetProductVariantByIDParams) (ProductVariant, error)
	GetProductVariantList(ctx context.Context, arg GetProductVariantListParams) ([]GetProductVariantListRow, error)
	GetProductVariantsByProductID(ctx context.Context, arg GetProductVariantsByProductIDParams) ([]ProductVariant, error)
	GetRatingReplies(ctx context.Context, id uuid.UUID) (RatingReply, error)
	GetRatingRepliesByRatingID(ctx context.Context, ratingID uuid.UUID) ([]GetRatingRepliesByRatingIDRow, error)
	GetRatingRepliesByUserID(ctx context.Context, replyBy uuid.UUID) ([]GetRatingRepliesByUserIDRow, error)
	GetRatingVote(ctx context.Context, arg GetRatingVoteParams) (RatingVote, error)
	GetRatingVotes(ctx context.Context, id uuid.UUID) (RatingVote, error)
	GetRatingVotesByRatingID(ctx context.Context, ratingID uuid.UUID) ([]RatingVote, error)
	GetRatingVotesByUserID(ctx context.Context, userID uuid.UUID) ([]RatingVote, error)
	GetRatingVotesCount(ctx context.Context, ratingID uuid.UUID) (int64, error)
	GetRatingVotesCountByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	// Roles Queries
	GetRoleByCode(ctx context.Context, code string) (UserRole, error)
	GetRoleByID(ctx context.Context, id uuid.UUID) (UserRole, error)
	GetSession(ctx context.Context, id uuid.UUID) (UserSession, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (UserSession, error)
	GetShippingMethodByID(ctx context.Context, id uuid.UUID) (ShippingMethod, error)
	GetShippingMethods(ctx context.Context, isActive *bool) ([]ShippingMethod, error)
	GetShippingRateByID(ctx context.Context, id uuid.UUID) (GetShippingRateByIDRow, error)
	GetShippingRates(ctx context.Context, isActive *bool) ([]GetShippingRatesRow, error)
	GetShippingRatesByZone(ctx context.Context, shippingZoneID uuid.UUID) ([]GetShippingRatesByZoneRow, error)
	GetShippingZoneByID(ctx context.Context, id uuid.UUID) (ShippingZone, error)
	GetShippingZones(ctx context.Context, isActive *bool) ([]ShippingZone, error)
	GetTopUsedDiscounts(ctx context.Context, arg GetTopUsedDiscountsParams) ([]Discount, error)
	GetTotalDiscountGiven(ctx context.Context, discountID uuid.UUID) (pgtype.Numeric, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUserDetailsByID(ctx context.Context, id uuid.UUID) (GetUserDetailsByIDRow, error)
	GetUserTotalSpent(ctx context.Context, userID uuid.UUID) (pgtype.Numeric, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error)
	GetUsersUsingDiscount(ctx context.Context, arg GetUsersUsingDiscountParams) ([]uuid.UUID, error)
	GetVariantDetailByID(ctx context.Context, arg GetVariantDetailByIDParams) ([]GetVariantDetailByIDRow, error)
	GetVerifyEmailByID(ctx context.Context, id uuid.UUID) (EmailVerification, error)
	GetVerifyEmailByVerifyCode(ctx context.Context, verifyCode string) (EmailVerification, error)
	IncrementDiscountUsage(ctx context.Context, id uuid.UUID) error
	InsertBulkProductImages(ctx context.Context, arg []InsertBulkProductImagesParams) (int64, error)
	InsertDiscount(ctx context.Context, arg InsertDiscountParams) (uuid.UUID, error)
	InsertDiscountRule(ctx context.Context, arg InsertDiscountRuleParams) (uuid.UUID, error)
	InsertProductImage(ctx context.Context, arg InsertProductImageParams) (ProductImage, error)
	InsertProductRating(ctx context.Context, arg InsertProductRatingParams) (ProductRating, error)
	InsertRatingReply(ctx context.Context, arg InsertRatingReplyParams) (RatingReply, error)
	InsertRatingVotes(ctx context.Context, arg InsertRatingVotesParams) (RatingVote, error)
	InsertSession(ctx context.Context, arg InsertSessionParams) (UserSession, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListPaymentMethods(ctx context.Context) ([]PaymentMethod, error)
	MaxPreviousOrderByUserID(ctx context.Context, userID uuid.UUID) (Order, error)
	ReactivateDiscount(ctx context.Context, id uuid.UUID) error
	RemoveDiscountUsage(ctx context.Context, arg RemoveDiscountUsageParams) error
	RemoveProductFromCart(ctx context.Context, arg RemoveProductFromCartParams) error
	RemoveProductsFromCategory(ctx context.Context, productID uuid.UUID) error
	RemoveProductsFromCollection(ctx context.Context, productID uuid.UUID) error
	ResetPrimaryAddress(ctx context.Context, userID uuid.UUID) error
	SeedAddresses(ctx context.Context, arg []SeedAddressesParams) (int64, error)
	SeedBrands(ctx context.Context, arg []SeedBrandsParams) (int64, error)
	SeedCategories(ctx context.Context, arg []SeedCategoriesParams) (int64, error)
	SeedCollections(ctx context.Context, arg []SeedCollectionsParams) (int64, error)
	SeedDiscounts(ctx context.Context, arg []SeedDiscountsParams) (int64, error)
	SeedShippingMethods(ctx context.Context, arg []SeedShippingMethodsParams) (int64, error)
	SeedShippingZones(ctx context.Context, arg []SeedShippingZonesParams) (int64, error)
	SeedUsers(ctx context.Context, arg []SeedUsersParams) (int64, error)
	SetPrimaryAddress(ctx context.Context, arg SetPrimaryAddressParams) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UserAddress, error)
	UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error)
	UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) (AttributeValue, error)
	UpdateBrandWith(ctx context.Context, arg UpdateBrandWithParams) (Brand, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCartTimestamp(ctx context.Context, id uuid.UUID) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCollectionWith(ctx context.Context, arg UpdateCollectionWithParams) (Collection, error)
	UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (Discount, error)
	UpdateDiscountRule(ctx context.Context, arg UpdateDiscountRuleParams) (DiscountRule, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (uuid.UUID, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdatePaymentTransaction(ctx context.Context, arg UpdatePaymentTransactionParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error
	UpdateProductPurchasedCount(ctx context.Context, arg UpdateProductPurchasedCountParams) (*int32, error)
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) (ProductRating, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (ProductVariant, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateRatingReplies(ctx context.Context, arg UpdateRatingRepliesParams) (RatingReply, error)
	UpdateRatingVote(ctx context.Context, arg UpdateRatingVoteParams) (RatingVote, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (UserSession, error)
	UpdateShippingMethod(ctx context.Context, arg UpdateShippingMethodParams) (ShippingMethod, error)
	UpdateShippingRate(ctx context.Context, arg UpdateShippingRateParams) (ShippingRate, error)
	UpdateShippingZone(ctx context.Context, arg UpdateShippingZoneParams) (ShippingZone, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (EmailVerification, error)
}

var _ Querier = (*Queries)(nil)
