// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package repository

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddBulkAttributes(ctx context.Context, name []string) (int64, error)
	AddBulkProducts(ctx context.Context, arg []AddBulkProductsParams) (int64, error)
	AddDiscountToCategory(ctx context.Context, arg AddDiscountToCategoryParams) (DiscountCategory, error)
	AddDiscountToProduct(ctx context.Context, arg AddDiscountToProductParams) (DiscountProduct, error)
	AddDiscountToUser(ctx context.Context, arg AddDiscountToUserParams) (DiscountUser, error)
	ArchiveProduct(ctx context.Context, arg ArchiveProductParams) error
	ArchiveProductVariant(ctx context.Context, arg ArchiveProductVariantParams) error
	AssociateDiscountWithOrder(ctx context.Context, arg AssociateDiscountWithOrderParams) (OrderDiscount, error)
	CheckoutCart(ctx context.Context, arg CheckoutCartParams) error
	ClearCart(ctx context.Context, id uuid.UUID) error
	CountAddresses(ctx context.Context) (int64, error)
	CountAttributes(ctx context.Context) (int64, error)
	CountBrands(ctx context.Context) (int64, error)
	CountCartItems(ctx context.Context, id uuid.UUID) (int64, error)
	CountCategories(ctx context.Context) (int64, error)
	CountCollections(ctx context.Context) (int64, error)
	CountOrders(ctx context.Context, arg CountOrdersParams) (int64, error)
	CountProductRatings(ctx context.Context, productID uuid.UUID) (int64, error)
	CountProducts(ctx context.Context, arg CountProductsParams) (int64, error)
	CountUsers(ctx context.Context) (int64, error)
	// User Address Queries
	CreateAddress(ctx context.Context, arg CreateAddressParams) (UserAddress, error)
	CreateAttribute(ctx context.Context, name string) (Attribute, error)
	// Attribute values
	CreateAttributeValue(ctx context.Context, arg CreateAttributeValueParams) (AttributeValue, error)
	CreateBrand(ctx context.Context, arg CreateBrandParams) (Brand, error)
	CreateBulkOrderItems(ctx context.Context, arg []CreateBulkOrderItemsParams) (int64, error)
	CreateBulkProductVariantAttribute(ctx context.Context, arg []CreateBulkProductVariantAttributeParams) (int64, error)
	CreateBulkProductVariants(ctx context.Context, arg []CreateBulkProductVariantsParams) (int64, error)
	CreateCart(ctx context.Context, arg CreateCartParams) (Cart, error)
	// Cart Item Section
	CreateCartItem(ctx context.Context, arg CreateCartItemParams) (CartItem, error)
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCollection(ctx context.Context, arg CreateCollectionParams) (Collection, error)
	CreateDiscount(ctx context.Context, arg CreateDiscountParams) (Discount, error)
	CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error)
	CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error)
	CreatePayment(ctx context.Context, arg CreatePaymentParams) (Payment, error)
	// Payment Transactions --
	CreatePaymentTransaction(ctx context.Context, arg CreatePaymentTransactionParams) (PaymentTransaction, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	// Product Variant attributes
	CreateProductVariantAttribute(ctx context.Context, arg CreateProductVariantAttributeParams) (VariantAttributeValue, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	// Verification Token Queries
	CreateVerifyEmail(ctx context.Context, arg CreateVerifyEmailParams) (VerifyEmail, error)
	DeleteAddress(ctx context.Context, arg DeleteAddressParams) error
	DeleteAttribute(ctx context.Context, id int32) error
	DeleteAttributeValue(ctx context.Context, id int32) error
	DeleteBrand(ctx context.Context, id uuid.UUID) error
	DeleteCategory(ctx context.Context, id uuid.UUID) error
	DeleteCollection(ctx context.Context, id uuid.UUID) error
	DeleteImageAssignments(ctx context.Context, arg DeleteImageAssignmentsParams) error
	DeleteOrder(ctx context.Context, id uuid.UUID) error
	DeletePayment(ctx context.Context, id uuid.UUID) error
	DeletePaymentTransaction(ctx context.Context, id uuid.UUID) error
	DeleteProduct(ctx context.Context, id uuid.UUID) error
	DeleteProductImage(ctx context.Context, id int32) error
	DeleteProductImageAssignment(ctx context.Context, arg DeleteProductImageAssignmentParams) error
	DeleteProductRating(ctx context.Context, id uuid.UUID) error
	DeleteProductVariant(ctx context.Context, id uuid.UUID) error
	DeleteProductVariantAttributes(ctx context.Context, variantID uuid.UUID) error
	DeleteRatingReplies(ctx context.Context, id uuid.UUID) error
	DeleteRatingVotes(ctx context.Context, id int32) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetAddress(ctx context.Context, arg GetAddressParams) (UserAddress, error)
	GetAddresses(ctx context.Context, userID uuid.UUID) ([]UserAddress, error)
	GetAttrValuesByAttrIDs(ctx context.Context, ids []int32) ([]AttributeValue, error)
	GetAttributeByID(ctx context.Context, id int32) ([]GetAttributeByIDRow, error)
	GetAttributeByIDs(ctx context.Context, ids []int32) ([]Attribute, error)
	GetAttributeByName(ctx context.Context, name string) (Attribute, error)
	GetAttributeValueByID(ctx context.Context, id int32) (AttributeValue, error)
	GetAttributeValues(ctx context.Context, attributeID int32) ([]AttributeValue, error)
	GetAttributeValuesByIDs(ctx context.Context, ids []int32) ([]AttributeValue, error)
	GetAttributes(ctx context.Context, ids []int32) ([]GetAttributesRow, error)
	GetAvailableDiscountsForCategory(ctx context.Context, arg GetAvailableDiscountsForCategoryParams) ([]Discount, error)
	GetAvailableDiscountsForProduct(ctx context.Context, arg GetAvailableDiscountsForProductParams) ([]Discount, error)
	GetAvailableDiscountsForUser(ctx context.Context, arg GetAvailableDiscountsForUserParams) ([]Discount, error)
	GetBrandByID(ctx context.Context, id uuid.UUID) (Brand, error)
	GetBrandBySlug(ctx context.Context, slug string) (Brand, error)
	GetBrands(ctx context.Context, arg GetBrandsParams) ([]Brand, error)
	GetBrandsByIDs(ctx context.Context, arg GetBrandsByIDsParams) ([]GetBrandsByIDsRow, error)
	GetCart(ctx context.Context, arg GetCartParams) (Cart, error)
	GetCartItem(ctx context.Context, arg GetCartItemParams) (CartItem, error)
	GetCartItemByProductVariantID(ctx context.Context, arg GetCartItemByProductVariantIDParams) (CartItem, error)
	GetCartItems(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsRow, error)
	GetCartItemsForOrder(ctx context.Context, cartID uuid.UUID) ([]GetCartItemsForOrderRow, error)
	GetCategories(ctx context.Context, arg GetCategoriesParams) ([]Category, error)
	GetCategoriesForDiscount(ctx context.Context, arg GetCategoriesForDiscountParams) ([]Category, error)
	GetCategoryByID(ctx context.Context, id uuid.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCategoryProductsByID(ctx context.Context, id uuid.UUID) ([]GetCategoryProductsByIDRow, error)
	GetCollectionByID(ctx context.Context, id uuid.UUID) (Collection, error)
	GetCollectionByIDWithProducts(ctx context.Context, id uuid.UUID) ([]GetCollectionByIDWithProductsRow, error)
	GetCollectionBySlug(ctx context.Context, slug string) (Collection, error)
	GetCollections(ctx context.Context, arg GetCollectionsParams) ([]Collection, error)
	GetCollectionsByIDs(ctx context.Context, arg GetCollectionsByIDsParams) ([]GetCollectionsByIDsRow, error)
	GetDefaultAddress(ctx context.Context, userID uuid.UUID) (UserAddress, error)
	GetDiscountAmount(ctx context.Context, arg GetDiscountAmountParams) (pgtype.Numeric, error)
	GetDiscountByCode(ctx context.Context, code string) (Discount, error)
	GetDiscountByID(ctx context.Context, id uuid.UUID) (Discount, error)
	GetDiscountsForOrder(ctx context.Context, orderID uuid.UUID) ([]Discount, error)
	GetImageFromExternalID(ctx context.Context, externalID string) (GetImageFromExternalIDRow, error)
	GetImageFromID(ctx context.Context, arg GetImageFromIDParams) (GetImageFromIDRow, error)
	GetImagesByEntityID(ctx context.Context, entityID uuid.UUID) ([]GetImagesByEntityIDRow, error)
	GetLinkedProductsByCategory(ctx context.Context, arg GetLinkedProductsByCategoryParams) ([]GetLinkedProductsByCategoryRow, error)
	GetOrder(ctx context.Context, id uuid.UUID) (Order, error)
	GetOrderItemByID(ctx context.Context, id uuid.UUID) (GetOrderItemByIDRow, error)
	GetOrderProducts(ctx context.Context, orderID uuid.UUID) ([]GetOrderProductsRow, error)
	GetOrders(ctx context.Context, arg GetOrdersParams) ([]GetOrdersRow, error)
	GetPaymentByID(ctx context.Context, id uuid.UUID) (Payment, error)
	GetPaymentByOrderID(ctx context.Context, orderID uuid.UUID) (Payment, error)
	GetPaymentByPaymentIntentID(ctx context.Context, gatewayPaymentIntentID *string) (Payment, error)
	GetPaymentTransactionByID(ctx context.Context, id uuid.UUID) (PaymentTransaction, error)
	GetPaymentTransactionByPaymentID(ctx context.Context, paymentID uuid.UUID) (PaymentTransaction, error)
	GetProductByID(ctx context.Context, arg GetProductByIDParams) (Product, error)
	GetProductDetail(ctx context.Context, arg GetProductDetailParams) ([]GetProductDetailRow, error)
	GetProductImageByEntityID(ctx context.Context, entityID uuid.UUID) (GetProductImageByEntityIDRow, error)
	GetProductImagesAssigned(ctx context.Context, entityIds []uuid.UUID) ([]GetProductImagesAssignedRow, error)
	GetProductRating(ctx context.Context, id uuid.UUID) (ProductRating, error)
	GetProductRatings(ctx context.Context, arg GetProductRatingsParams) ([]GetProductRatingsRow, error)
	GetProductRatingsByUserID(ctx context.Context, arg GetProductRatingsByUserIDParams) ([]GetProductRatingsByUserIDRow, error)
	GetProductRatingsCount(ctx context.Context, productID uuid.UUID) (int64, error)
	GetProductVariantAttributeByID(ctx context.Context, variantID uuid.UUID) (VariantAttributeValue, error)
	GetProductVariantAttributes(ctx context.Context, variantID uuid.UUID) ([]VariantAttributeValue, error)
	GetProductVariantByID(ctx context.Context, id uuid.UUID) (ProductVariant, error)
	GetProductVariants(ctx context.Context, arg GetProductVariantsParams) ([]GetProductVariantsRow, error)
	GetProducts(ctx context.Context, arg GetProductsParams) ([]GetProductsRow, error)
	GetProductsForDiscount(ctx context.Context, arg GetProductsForDiscountParams) ([]Product, error)
	GetRatingReplies(ctx context.Context, id uuid.UUID) (RatingReply, error)
	GetRatingRepliesByRatingID(ctx context.Context, ratingID uuid.UUID) ([]GetRatingRepliesByRatingIDRow, error)
	GetRatingRepliesByUserID(ctx context.Context, replyBy uuid.UUID) ([]GetRatingRepliesByUserIDRow, error)
	GetRatingVotes(ctx context.Context, id int32) (RatingVote, error)
	GetRatingVotesByRatingID(ctx context.Context, ratingID uuid.UUID) ([]RatingVote, error)
	GetRatingVotesByUserID(ctx context.Context, userID uuid.UUID) ([]RatingVote, error)
	GetRatingVotesCount(ctx context.Context, ratingID uuid.UUID) (int64, error)
	GetRatingVotesCountByUserID(ctx context.Context, userID uuid.UUID) (int64, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetSessionByRefreshToken(ctx context.Context, refreshToken string) (Session, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	GetUserByUsername(ctx context.Context, username string) (User, error)
	GetUsersForDiscount(ctx context.Context, arg GetUsersForDiscountParams) ([]User, error)
	GetVerifyEmailByID(ctx context.Context, id int32) (VerifyEmail, error)
	GetVerifyEmailByVerifyCode(ctx context.Context, verifyCode string) (VerifyEmail, error)
	IncrementDiscountUsage(ctx context.Context, id uuid.UUID) (Discount, error)
	InsertBulkImageAssignments(ctx context.Context, arg []InsertBulkImageAssignmentsParams) (int64, error)
	InsertBulkImages(ctx context.Context, arg []InsertBulkImagesParams) (int64, error)
	InsertImage(ctx context.Context, arg InsertImageParams) (Image, error)
	InsertImageAssignment(ctx context.Context, arg InsertImageAssignmentParams) (ImageAssignment, error)
	InsertProductRating(ctx context.Context, arg InsertProductRatingParams) (ProductRating, error)
	InsertRatingReply(ctx context.Context, arg InsertRatingReplyParams) (RatingReply, error)
	InsertRatingVotes(ctx context.Context, arg InsertRatingVotesParams) (RatingVote, error)
	ListActiveDiscounts(ctx context.Context, arg ListActiveDiscountsParams) ([]Discount, error)
	ListAllDiscounts(ctx context.Context, arg ListAllDiscountsParams) ([]Discount, error)
	ListOrderItems(ctx context.Context, arg ListOrderItemsParams) ([]OrderItem, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	RemoveDiscountFromCategory(ctx context.Context, arg RemoveDiscountFromCategoryParams) error
	RemoveDiscountFromProduct(ctx context.Context, arg RemoveDiscountFromProductParams) error
	RemoveDiscountFromUser(ctx context.Context, arg RemoveDiscountFromUserParams) error
	RemoveProductFromCart(ctx context.Context, arg RemoveProductFromCartParams) error
	ResetPrimaryAddress(ctx context.Context, userID uuid.UUID) error
	SeedAddresses(ctx context.Context, arg []SeedAddressesParams) (int64, error)
	SeedCategories(ctx context.Context, arg []SeedCategoriesParams) (int64, error)
	SeedCollections(ctx context.Context, arg []SeedCollectionsParams) (int64, error)
	SeedUsers(ctx context.Context, arg []SeedUsersParams) (int64, error)
	SetPrimaryAddress(ctx context.Context, arg SetPrimaryAddressParams) error
	SoftDeleteDiscount(ctx context.Context, id uuid.UUID) error
	UpdateAddress(ctx context.Context, arg UpdateAddressParams) (UserAddress, error)
	UpdateAttribute(ctx context.Context, arg UpdateAttributeParams) (Attribute, error)
	UpdateAttributeValue(ctx context.Context, arg UpdateAttributeValueParams) (AttributeValue, error)
	UpdateBrandWith(ctx context.Context, arg UpdateBrandWithParams) (Brand, error)
	UpdateCartItemQuantity(ctx context.Context, arg UpdateCartItemQuantityParams) error
	UpdateCartTimestamp(ctx context.Context, id uuid.UUID) error
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCollectionWith(ctx context.Context, arg UpdateCollectionWithParams) (Collection, error)
	UpdateDiscount(ctx context.Context, arg UpdateDiscountParams) (Discount, error)
	UpdateOrder(ctx context.Context, arg UpdateOrderParams) (Order, error)
	UpdateOrderTotal(ctx context.Context, arg UpdateOrderTotalParams) (Order, error)
	UpdatePayment(ctx context.Context, arg UpdatePaymentParams) error
	UpdatePaymentTransaction(ctx context.Context, arg UpdatePaymentTransactionParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductImage(ctx context.Context, arg UpdateProductImageParams) error
	UpdateProductImageAssignment(ctx context.Context, arg UpdateProductImageAssignmentParams) error
	UpdateProductRating(ctx context.Context, arg UpdateProductRatingParams) (ProductRating, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (ProductVariant, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdateRatingReplies(ctx context.Context, arg UpdateRatingRepliesParams) (RatingReply, error)
	UpdateRatingVotes(ctx context.Context, arg UpdateRatingVotesParams) (RatingVote, error)
	UpdateSession(ctx context.Context, arg UpdateSessionParams) (Session, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
	UpdateVerifyEmail(ctx context.Context, arg UpdateVerifyEmailParams) (VerifyEmail, error)
}

var _ Querier = (*Queries)(nil)
