basePath: /api/v1
definitions:
  api.addProductToCartRequest:
    properties:
      cart_id:
        type: integer
      product_id:
        type: integer
      quantity:
        type: integer
    required:
    - cart_id
    - product_id
    - quantity
    type: object
  api.cartItem:
    properties:
      description:
        type: string
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
      product_id:
        type: integer
      quantity:
        type: integer
      sku:
        type: string
    type: object
  api.cartResponse:
    properties:
      cart_items:
        items:
          $ref: '#/definitions/api.cartItem'
        type: array
      checked_out:
        type: string
      created_at:
        type: string
      id:
        type: integer
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  api.checkoutRequest:
    properties:
      cart_id:
        type: integer
      is_cod:
        type: boolean
      payment_type:
        type: string
    required:
    - cart_id
    - is_cod
    - payment_type
    type: object
  api.createCartRequest:
    properties:
      user_id:
        type: integer
    required:
    - user_id
    type: object
  api.createUserRequest:
    properties:
      email:
        maxLength: 255
        minLength: 6
        type: string
      full_name:
        maxLength: 32
        minLength: 3
        type: string
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - email
    - full_name
    - password
    - username
    type: object
  api.createUserResponse:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      password_changed_at:
        type: string
      updated_at:
        type: string
      username:
        type: string
    type: object
  api.itemUpdate:
    properties:
      product_id:
        type: integer
      quantity:
        type: integer
    required:
    - product_id
    - quantity
    type: object
  api.listOrderResponse:
    properties:
      orders:
        items:
          $ref: '#/definitions/sqlc.Order'
        type: array
    type: object
  api.loginResponse:
    properties:
      refresh_token:
        type: string
      refresh_token_expire_at:
        type: string
      session_id:
        type: string
      token:
        type: string
      token_expire_at:
        type: string
      user:
        $ref: '#/definitions/api.createUserResponse'
    type: object
  api.loginUserRequest:
    properties:
      password:
        maxLength: 32
        minLength: 6
        type: string
      username:
        maxLength: 32
        minLength: 3
        type: string
    required:
    - password
    - username
    type: object
  api.productRequest:
    properties:
      description:
        maxLength: 1000
        minLength: 10
        type: string
      name:
        maxLength: 100
        minLength: 3
        type: string
      price:
        type: number
      sku:
        type: string
      stock:
        type: integer
    required:
    - description
    - name
    - price
    - sku
    - stock
    type: object
  api.productResponse:
    properties:
      created_at:
        type: string
      description:
        type: string
      id:
        type: integer
      image_url:
        type: string
      name:
        type: string
      price:
        type: number
      sku:
        type: string
      stock:
        type: integer
      updated_at:
        type: string
    type: object
  api.removeProductFromCartRequest:
    properties:
      cart_id:
        type: integer
      product_id:
        type: integer
    required:
    - cart_id
    - product_id
    type: object
  api.updateCartRequest:
    properties:
      cart_id:
        type: integer
      items:
        items:
          $ref: '#/definitions/api.itemUpdate'
        type: array
    required:
    - cart_id
    - items
    type: object
  api.updateUserRequest:
    properties:
      email:
        maxLength: 255
        minLength: 6
        type: string
      full_name:
        maxLength: 32
        minLength: 3
        type: string
      role:
        $ref: '#/definitions/sqlc.UserRole'
      user_id:
        minimum: 1
        type: integer
    required:
    - user_id
    type: object
  gin.H:
    additionalProperties: {}
    type: object
  pgtype.InfinityModifier:
    enum:
    - 1
    - 0
    - -1
    type: integer
    x-enum-varnames:
    - Infinity
    - Finite
    - NegativeInfinity
  pgtype.Int8:
    properties:
      int64:
        type: integer
      valid:
        type: boolean
    type: object
  pgtype.Timestamptz:
    properties:
      infinityModifier:
        $ref: '#/definitions/pgtype.InfinityModifier'
      time:
        type: string
      valid:
        type: boolean
    type: object
  sqlc.CreateUserRow:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      role:
        $ref: '#/definitions/sqlc.UserRole'
      updated_at:
        type: string
      username:
        type: string
      verified_email:
        type: boolean
      verified_phone:
        type: boolean
    type: object
  sqlc.Order:
    properties:
      cancelled_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      confirmed_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      created_at:
        type: string
      delivered_at:
        $ref: '#/definitions/pgtype.Timestamptz'
      id:
        type: integer
      is_cod:
        type: boolean
      payment_status:
        $ref: '#/definitions/sqlc.PaymentStatus'
      payment_type:
        $ref: '#/definitions/sqlc.PaymentType'
      shipping_id:
        $ref: '#/definitions/pgtype.Int8'
      status:
        $ref: '#/definitions/sqlc.OrderStatus'
      updated_at:
        type: string
      user_id:
        type: integer
    type: object
  sqlc.OrderStatus:
    enum:
    - wait_for_confirming
    - confirmed
    - delivering
    - delivered
    - cancelled
    - refunded
    - completed
    type: string
    x-enum-varnames:
    - OrderStatusWaitForConfirming
    - OrderStatusConfirmed
    - OrderStatusDelivering
    - OrderStatusDelivered
    - OrderStatusCancelled
    - OrderStatusRefunded
    - OrderStatusCompleted
  sqlc.PaymentStatus:
    enum:
    - not_paid
    - paid
    type: string
    x-enum-varnames:
    - PaymentStatusNotPaid
    - PaymentStatusPaid
  sqlc.PaymentType:
    enum:
    - cash
    - transfer
    type: string
    x-enum-varnames:
    - PaymentTypeCash
    - PaymentTypeTransfer
  sqlc.UpdateUserRow:
    properties:
      created_at:
        type: string
      email:
        type: string
      full_name:
        type: string
      id:
        type: integer
      role:
        $ref: '#/definitions/sqlc.UserRole'
      updated_at:
        type: string
      username:
        type: string
      verified_email:
        type: boolean
      verified_phone:
        type: boolean
    type: object
  sqlc.UserRole:
    enum:
    - admin
    - user
    type: string
    x-enum-varnames:
    - UserRoleAdmin
    - UserRoleUser
host: localhost:4000
info:
  contact: {}
  description: This is a sample server for a simple e-commerce API.
  title: E-Commerce API
paths:
  /carts:
    get:
      consumes:
      - application/json
      description: get cart details by user ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.cartResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get cart details by user ID
      tags:
      - carts
    post:
      consumes:
      - application/json
      description: create a new cart for a user
      parameters:
      - description: Cart input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.createCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.cartResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create a new cart
      tags:
      - carts
  /carts/products:
    delete:
      consumes:
      - application/json
      description: remove a product from the cart
      parameters:
      - description: Remove product from cart input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.removeProductFromCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Remove a product from the cart
      tags:
      - carts
    post:
      consumes:
      - application/json
      description: update product items in the cart
      parameters:
      - description: Update cart items input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.checkoutRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sqlc.Order'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update product items in the cart
      tags:
      - carts
    put:
      consumes:
      - application/json
      description: update product items in the cart
      parameters:
      - description: Update cart items input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.updateCartRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update product items in the cart
      tags:
      - carts
  /orders:
    get:
      consumes:
      - application/json
      description: List orders of the current user
      parameters:
      - description: Limit
        in: query
        name: limit
        type: integer
      - description: Offset
        in: query
        name: offset
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.listOrderResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      security:
      - ApiKeyAuth: []
      summary: List orders
      tags:
      - orders
  /products:
    get:
      consumes:
      - application/json
      description: get list of products
      parameters:
      - description: Page number
        in: query
        name: page
        required: true
        type: integer
      - description: Page size
        in: query
        name: page_size
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/api.productResponse'
            type: array
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get list of products
      tags:
      - products
    post:
      consumes:
      - application/json
      description: create a new product with the input payload
      parameters:
      - description: Product input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.productRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.productResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Create a new product
      tags:
      - products
  /products/{product_id}:
    delete:
      consumes:
      - application/json
      description: remove a product by ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Remove a product by ID
      tags:
      - products
    get:
      consumes:
      - application/json
      description: get a product detail by ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.productResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Get a product detail by ID
      tags:
      - product detail
    put:
      consumes:
      - application/json
      description: update a product by ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      - description: Product input
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.productRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.productResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Update a product by ID
      tags:
      - products
  /products/{product_id}/upload-image:
    post:
      consumes:
      - application/json
      description: upload a product image by ID
      parameters:
      - description: Product ID
        in: path
        name: product_id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/gin.H'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/gin.H'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/gin.H'
      summary: Upload a product image by ID
      tags:
      - products
  /users:
    post:
      consumes:
      - application/json
      description: Create a new user
      parameters:
      - description: User info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.createUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sqlc.CreateUserRow'
      summary: Create a new user
      tags:
      - users
  /users/{id}:
    patch:
      consumes:
      - application/json
      description: Update user info
      parameters:
      - description: User info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.updateUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/sqlc.UpdateUserRow'
      summary: Update user info
      tags:
      - users
  /users/login:
    post:
      consumes:
      - application/json
      description: Login to the system
      parameters:
      - description: User info
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/api.loginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.loginResponse'
      summary: Login to the system
      tags:
      - users
swagger: "2.0"
